package fnt.repository.dao;

import fnt.repository.model.FsQdfPaymentInfo;
import fnt.repository.model.FsQdfPaymentInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsQdfPaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int countByExample(FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int deleteByExample(FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int insert(FsQdfPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int insertSelective(FsQdfPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    List<FsQdfPaymentInfo> selectByExample(FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    FsQdfPaymentInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfPaymentInfo record, @Param("example") FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int updateByExample(@Param("record") FsQdfPaymentInfo record, @Param("example") FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int updateByPrimaryKeySelective(FsQdfPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    int updateByPrimaryKey(FsQdfPaymentInfo record);
}