package fnt.repository.dao;

import fnt.repository.model.FsQdfPendingVchInfo;
import fnt.repository.model.FsQdfPendingVchInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsQdfPendingVchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int countByExample(FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int deleteByExample(FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int insert(FsQdfPendingVchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int insertSelective(FsQdfPendingVchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    List<FsQdfPendingVchInfo> selectByExample(FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    FsQdfPendingVchInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfPendingVchInfo record, @Param("example") FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int updateByExample(@Param("record") FsQdfPendingVchInfo record, @Param("example") FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int updateByPrimaryKeySelective(FsQdfPendingVchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    int updateByPrimaryKey(FsQdfPendingVchInfo record);
}