package fnt.repository.dao;

import fnt.repository.model.FsQdfChkTxn;
import fnt.repository.model.FsQdfChkTxnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsQdfChkTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int countByExample(FsQdfChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int deleteByExample(FsQdfChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int insert(FsQdfChkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int insertSelective(FsQdfChkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    List<FsQdfChkTxn> selectByExample(FsQdfChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    FsQdfChkTxn selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfChkTxn record, @Param("example") FsQdfChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int updateByExample(@Param("record") FsQdfChkTxn record, @Param("example") FsQdfChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int updateByPrimaryKeySelective(FsQdfChkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_TXN
     *
     * @mbggenerated Fri Jul 12 15:27:53 CST 2013
     */
    int updateByPrimaryKey(FsQdfChkTxn record);
}