package fnt.repository.dao;

import fnt.repository.model.FsQdfShareInfo;
import fnt.repository.model.FsQdfShareInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsQdfShareInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int countByExample(FsQdfShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int deleteByExample(FsQdfShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int insert(FsQdfShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int insertSelective(FsQdfShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    List<FsQdfShareInfo> selectByExample(FsQdfShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    FsQdfShareInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfShareInfo record, @Param("example") FsQdfShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int updateByExample(@Param("record") FsQdfShareInfo record, @Param("example") FsQdfShareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int updateByPrimaryKeySelective(FsQdfShareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_SHARE_INFO
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    int updateByPrimaryKey(FsQdfShareInfo record);
}