package fnt.repository.model;

public class FsQdfSysCtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.SCT_SEQNO
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String sctSeqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.BANK_ID
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.SYS_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String sysSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.TXN_DATE
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.CBS_CHK_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String cbsChkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.WSYS_CHK_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String wsysChkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.TXN_SEQ
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private Integer txnSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String hostChkDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.WSYS_CHK_DT
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String wsysChkDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.USER_ID
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.PASSWORD
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.REMARK
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.IS_MULTI_BOOK
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String isMultiBook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.CBS_ACTNO
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String cbsActno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.CBS_ACTNAM
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String cbsActnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SYS_CTL.AREA_CODE
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.SCT_SEQNO
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.SCT_SEQNO
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getSctSeqno() {
        return sctSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.SCT_SEQNO
     *
     * @param sctSeqno the value for FIS.FS_QDF_SYS_CTL.SCT_SEQNO
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setSctSeqno(String sctSeqno) {
        this.sctSeqno = sctSeqno == null ? null : sctSeqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.BANK_ID
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.BANK_ID
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.BANK_ID
     *
     * @param bankId the value for FIS.FS_QDF_SYS_CTL.BANK_ID
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.BANK_NAME
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.BANK_NAME
     *
     * @param bankName the value for FIS.FS_QDF_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.SYS_STS
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.SYS_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getSysSts() {
        return sysSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.SYS_STS
     *
     * @param sysSts the value for FIS.FS_QDF_SYS_CTL.SYS_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setSysSts(String sysSts) {
        this.sysSts = sysSts == null ? null : sysSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.TXN_DATE
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.TXN_DATE
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.TXN_DATE
     *
     * @param txnDate the value for FIS.FS_QDF_SYS_CTL.TXN_DATE
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.CBS_CHK_STS
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.CBS_CHK_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getCbsChkSts() {
        return cbsChkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.CBS_CHK_STS
     *
     * @param cbsChkSts the value for FIS.FS_QDF_SYS_CTL.CBS_CHK_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setCbsChkSts(String cbsChkSts) {
        this.cbsChkSts = cbsChkSts == null ? null : cbsChkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.WSYS_CHK_STS
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.WSYS_CHK_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getWsysChkSts() {
        return wsysChkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.WSYS_CHK_STS
     *
     * @param wsysChkSts the value for FIS.FS_QDF_SYS_CTL.WSYS_CHK_STS
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setWsysChkSts(String wsysChkSts) {
        this.wsysChkSts = wsysChkSts == null ? null : wsysChkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.TXN_SEQ
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.TXN_SEQ
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public Integer getTxnSeq() {
        return txnSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.TXN_SEQ
     *
     * @param txnSeq the value for FIS.FS_QDF_SYS_CTL.TXN_SEQ
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setTxnSeq(Integer txnSeq) {
        this.txnSeq = txnSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.HOST_CHK_DT
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getHostChkDt() {
        return hostChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.HOST_CHK_DT
     *
     * @param hostChkDt the value for FIS.FS_QDF_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setHostChkDt(String hostChkDt) {
        this.hostChkDt = hostChkDt == null ? null : hostChkDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.WSYS_CHK_DT
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.WSYS_CHK_DT
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getWsysChkDt() {
        return wsysChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.WSYS_CHK_DT
     *
     * @param wsysChkDt the value for FIS.FS_QDF_SYS_CTL.WSYS_CHK_DT
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setWsysChkDt(String wsysChkDt) {
        this.wsysChkDt = wsysChkDt == null ? null : wsysChkDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.USER_ID
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.USER_ID
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.USER_ID
     *
     * @param userId the value for FIS.FS_QDF_SYS_CTL.USER_ID
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.PASSWORD
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.PASSWORD
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.PASSWORD
     *
     * @param password the value for FIS.FS_QDF_SYS_CTL.PASSWORD
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.REMARK
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.REMARK
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.REMARK
     *
     * @param remark the value for FIS.FS_QDF_SYS_CTL.REMARK
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.IS_MULTI_BOOK
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.IS_MULTI_BOOK
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getIsMultiBook() {
        return isMultiBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.IS_MULTI_BOOK
     *
     * @param isMultiBook the value for FIS.FS_QDF_SYS_CTL.IS_MULTI_BOOK
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setIsMultiBook(String isMultiBook) {
        this.isMultiBook = isMultiBook == null ? null : isMultiBook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.CBS_ACTNO
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.CBS_ACTNO
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getCbsActno() {
        return cbsActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.CBS_ACTNO
     *
     * @param cbsActno the value for FIS.FS_QDF_SYS_CTL.CBS_ACTNO
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setCbsActno(String cbsActno) {
        this.cbsActno = cbsActno == null ? null : cbsActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.CBS_ACTNAM
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.CBS_ACTNAM
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getCbsActnam() {
        return cbsActnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.CBS_ACTNAM
     *
     * @param cbsActnam the value for FIS.FS_QDF_SYS_CTL.CBS_ACTNAM
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setCbsActnam(String cbsActnam) {
        this.cbsActnam = cbsActnam == null ? null : cbsActnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SYS_CTL.AREA_CODE
     *
     * @return the value of FIS.FS_QDF_SYS_CTL.AREA_CODE
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SYS_CTL.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_QDF_SYS_CTL.AREA_CODE
     *
     * @mbggenerated Thu Jun 27 19:30:03 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }
}