package fnt.repository.model;

import java.math.BigDecimal;

public class FsQdfChkVch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.PKID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.PJZL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String pjzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.JKSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String jksbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.WTZSDWBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String wtzsdwbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.SRXMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String srxmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.SL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.JE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal je;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.YHSKRQ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String yhskrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.JKFS
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String jkfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.BYZD1
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.BYZD2
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.BYZD3
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.BYZD4
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.BYZD5
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.BYZD6
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.DZSBYY
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String dzsbyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.CHK_STS
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String chkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.CHK_DATE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String chkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_CHK_VCH.DATA_SYS_ID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String dataSysId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.PKID
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.PKID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.PKID
     *
     * @param pkid the value for FIS.FS_QDF_CHK_VCH.PKID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.PJZL
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.PJZL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getPjzl() {
        return pjzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.PJZL
     *
     * @param pjzl the value for FIS.FS_QDF_CHK_VCH.PJZL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setPjzl(String pjzl) {
        this.pjzl = pjzl == null ? null : pjzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.JKSBH
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.JKSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getJksbh() {
        return jksbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.JKSBH
     *
     * @param jksbh the value for FIS.FS_QDF_CHK_VCH.JKSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJksbh(String jksbh) {
        this.jksbh = jksbh == null ? null : jksbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.WTZSDWBM
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.WTZSDWBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getWtzsdwbm() {
        return wtzsdwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.WTZSDWBM
     *
     * @param wtzsdwbm the value for FIS.FS_QDF_CHK_VCH.WTZSDWBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setWtzsdwbm(String wtzsdwbm) {
        this.wtzsdwbm = wtzsdwbm == null ? null : wtzsdwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.SRXMBM
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.SRXMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getSrxmbm() {
        return srxmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.SRXMBM
     *
     * @param srxmbm the value for FIS.FS_QDF_CHK_VCH.SRXMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setSrxmbm(String srxmbm) {
        this.srxmbm = srxmbm == null ? null : srxmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.SL
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.SL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.SL
     *
     * @param sl the value for FIS.FS_QDF_CHK_VCH.SL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.JE
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.JE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getJe() {
        return je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.JE
     *
     * @param je the value for FIS.FS_QDF_CHK_VCH.JE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJe(BigDecimal je) {
        this.je = je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.YHSKRQ
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.YHSKRQ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getYhskrq() {
        return yhskrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.YHSKRQ
     *
     * @param yhskrq the value for FIS.FS_QDF_CHK_VCH.YHSKRQ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setYhskrq(String yhskrq) {
        this.yhskrq = yhskrq == null ? null : yhskrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.JKFS
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.JKFS
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getJkfs() {
        return jkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.JKFS
     *
     * @param jkfs the value for FIS.FS_QDF_CHK_VCH.JKFS
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJkfs(String jkfs) {
        this.jkfs = jkfs == null ? null : jkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.BYZD1
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.BYZD1
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd1() {
        return byzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.BYZD1
     *
     * @param byzd1 the value for FIS.FS_QDF_CHK_VCH.BYZD1
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd1(String byzd1) {
        this.byzd1 = byzd1 == null ? null : byzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.BYZD2
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.BYZD2
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd2() {
        return byzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.BYZD2
     *
     * @param byzd2 the value for FIS.FS_QDF_CHK_VCH.BYZD2
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd2(String byzd2) {
        this.byzd2 = byzd2 == null ? null : byzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.BYZD3
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.BYZD3
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd3() {
        return byzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.BYZD3
     *
     * @param byzd3 the value for FIS.FS_QDF_CHK_VCH.BYZD3
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd3(String byzd3) {
        this.byzd3 = byzd3 == null ? null : byzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.BYZD4
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.BYZD4
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd4() {
        return byzd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.BYZD4
     *
     * @param byzd4 the value for FIS.FS_QDF_CHK_VCH.BYZD4
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd4(String byzd4) {
        this.byzd4 = byzd4 == null ? null : byzd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.BYZD5
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.BYZD5
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd5() {
        return byzd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.BYZD5
     *
     * @param byzd5 the value for FIS.FS_QDF_CHK_VCH.BYZD5
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd5(String byzd5) {
        this.byzd5 = byzd5 == null ? null : byzd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.BYZD6
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.BYZD6
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd6() {
        return byzd6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.BYZD6
     *
     * @param byzd6 the value for FIS.FS_QDF_CHK_VCH.BYZD6
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd6(String byzd6) {
        this.byzd6 = byzd6 == null ? null : byzd6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.DZSBYY
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.DZSBYY
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getDzsbyy() {
        return dzsbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.DZSBYY
     *
     * @param dzsbyy the value for FIS.FS_QDF_CHK_VCH.DZSBYY
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setDzsbyy(String dzsbyy) {
        this.dzsbyy = dzsbyy == null ? null : dzsbyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.CHK_STS
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.CHK_STS
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getChkSts() {
        return chkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.CHK_STS
     *
     * @param chkSts the value for FIS.FS_QDF_CHK_VCH.CHK_STS
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setChkSts(String chkSts) {
        this.chkSts = chkSts == null ? null : chkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.CHK_DATE
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.CHK_DATE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getChkDate() {
        return chkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.CHK_DATE
     *
     * @param chkDate the value for FIS.FS_QDF_CHK_VCH.CHK_DATE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setChkDate(String chkDate) {
        this.chkDate = chkDate == null ? null : chkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_CHK_VCH.DATA_SYS_ID
     *
     * @return the value of FIS.FS_QDF_CHK_VCH.DATA_SYS_ID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getDataSysId() {
        return dataSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_CHK_VCH.DATA_SYS_ID
     *
     * @param dataSysId the value for FIS.FS_QDF_CHK_VCH.DATA_SYS_ID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setDataSysId(String dataSysId) {
        this.dataSysId = dataSysId == null ? null : dataSysId.trim();
    }
}