package fnt.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FsQdfPendingVchInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public FsQdfPendingVchInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andXzqhIsNull() {
            addCriterion("XZQH is null");
            return (Criteria) this;
        }

        public Criteria andXzqhIsNotNull() {
            addCriterion("XZQH is not null");
            return (Criteria) this;
        }

        public Criteria andXzqhEqualTo(String value) {
            addCriterion("XZQH =", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotEqualTo(String value) {
            addCriterion("XZQH <>", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhGreaterThan(String value) {
            addCriterion("XZQH >", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhGreaterThanOrEqualTo(String value) {
            addCriterion("XZQH >=", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLessThan(String value) {
            addCriterion("XZQH <", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLessThanOrEqualTo(String value) {
            addCriterion("XZQH <=", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLike(String value) {
            addCriterion("XZQH like", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotLike(String value) {
            addCriterion("XZQH not like", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhIn(List<String> values) {
            addCriterion("XZQH in", values, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotIn(List<String> values) {
            addCriterion("XZQH not in", values, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhBetween(String value1, String value2) {
            addCriterion("XZQH between", value1, value2, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotBetween(String value1, String value2) {
            addCriterion("XZQH not between", value1, value2, "xzqh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhIsNull() {
            addCriterion("DBPYWXH is null");
            return (Criteria) this;
        }

        public Criteria andDbpywxhIsNotNull() {
            addCriterion("DBPYWXH is not null");
            return (Criteria) this;
        }

        public Criteria andDbpywxhEqualTo(String value) {
            addCriterion("DBPYWXH =", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhNotEqualTo(String value) {
            addCriterion("DBPYWXH <>", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhGreaterThan(String value) {
            addCriterion("DBPYWXH >", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhGreaterThanOrEqualTo(String value) {
            addCriterion("DBPYWXH >=", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhLessThan(String value) {
            addCriterion("DBPYWXH <", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhLessThanOrEqualTo(String value) {
            addCriterion("DBPYWXH <=", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhLike(String value) {
            addCriterion("DBPYWXH like", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhNotLike(String value) {
            addCriterion("DBPYWXH not like", value, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhIn(List<String> values) {
            addCriterion("DBPYWXH in", values, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhNotIn(List<String> values) {
            addCriterion("DBPYWXH not in", values, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhBetween(String value1, String value2) {
            addCriterion("DBPYWXH between", value1, value2, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andDbpywxhNotBetween(String value1, String value2) {
            addCriterion("DBPYWXH not between", value1, value2, "dbpywxh");
            return (Criteria) this;
        }

        public Criteria andJylxIsNull() {
            addCriterion("JYLX is null");
            return (Criteria) this;
        }

        public Criteria andJylxIsNotNull() {
            addCriterion("JYLX is not null");
            return (Criteria) this;
        }

        public Criteria andJylxEqualTo(String value) {
            addCriterion("JYLX =", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxNotEqualTo(String value) {
            addCriterion("JYLX <>", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxGreaterThan(String value) {
            addCriterion("JYLX >", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxGreaterThanOrEqualTo(String value) {
            addCriterion("JYLX >=", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxLessThan(String value) {
            addCriterion("JYLX <", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxLessThanOrEqualTo(String value) {
            addCriterion("JYLX <=", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxLike(String value) {
            addCriterion("JYLX like", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxNotLike(String value) {
            addCriterion("JYLX not like", value, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxIn(List<String> values) {
            addCriterion("JYLX in", values, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxNotIn(List<String> values) {
            addCriterion("JYLX not in", values, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxBetween(String value1, String value2) {
            addCriterion("JYLX between", value1, value2, "jylx");
            return (Criteria) this;
        }

        public Criteria andJylxNotBetween(String value1, String value2) {
            addCriterion("JYLX not between", value1, value2, "jylx");
            return (Criteria) this;
        }

        public Criteria andCzzhzhIsNull() {
            addCriterion("CZZHZH is null");
            return (Criteria) this;
        }

        public Criteria andCzzhzhIsNotNull() {
            addCriterion("CZZHZH is not null");
            return (Criteria) this;
        }

        public Criteria andCzzhzhEqualTo(String value) {
            addCriterion("CZZHZH =", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotEqualTo(String value) {
            addCriterion("CZZHZH <>", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhGreaterThan(String value) {
            addCriterion("CZZHZH >", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhGreaterThanOrEqualTo(String value) {
            addCriterion("CZZHZH >=", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhLessThan(String value) {
            addCriterion("CZZHZH <", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhLessThanOrEqualTo(String value) {
            addCriterion("CZZHZH <=", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhLike(String value) {
            addCriterion("CZZHZH like", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotLike(String value) {
            addCriterion("CZZHZH not like", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhIn(List<String> values) {
            addCriterion("CZZHZH in", values, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotIn(List<String> values) {
            addCriterion("CZZHZH not in", values, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhBetween(String value1, String value2) {
            addCriterion("CZZHZH between", value1, value2, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotBetween(String value1, String value2) {
            addCriterion("CZZHZH not between", value1, value2, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andZsdwbmIsNull() {
            addCriterion("ZSDWBM is null");
            return (Criteria) this;
        }

        public Criteria andZsdwbmIsNotNull() {
            addCriterion("ZSDWBM is not null");
            return (Criteria) this;
        }

        public Criteria andZsdwbmEqualTo(String value) {
            addCriterion("ZSDWBM =", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmNotEqualTo(String value) {
            addCriterion("ZSDWBM <>", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmGreaterThan(String value) {
            addCriterion("ZSDWBM >", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmGreaterThanOrEqualTo(String value) {
            addCriterion("ZSDWBM >=", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmLessThan(String value) {
            addCriterion("ZSDWBM <", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmLessThanOrEqualTo(String value) {
            addCriterion("ZSDWBM <=", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmLike(String value) {
            addCriterion("ZSDWBM like", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmNotLike(String value) {
            addCriterion("ZSDWBM not like", value, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmIn(List<String> values) {
            addCriterion("ZSDWBM in", values, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmNotIn(List<String> values) {
            addCriterion("ZSDWBM not in", values, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmBetween(String value1, String value2) {
            addCriterion("ZSDWBM between", value1, value2, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andZsdwbmNotBetween(String value1, String value2) {
            addCriterion("ZSDWBM not between", value1, value2, "zsdwbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmIsNull() {
            addCriterion("DWZGBMBM is null");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmIsNotNull() {
            addCriterion("DWZGBMBM is not null");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmEqualTo(String value) {
            addCriterion("DWZGBMBM =", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmNotEqualTo(String value) {
            addCriterion("DWZGBMBM <>", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmGreaterThan(String value) {
            addCriterion("DWZGBMBM >", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmGreaterThanOrEqualTo(String value) {
            addCriterion("DWZGBMBM >=", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmLessThan(String value) {
            addCriterion("DWZGBMBM <", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmLessThanOrEqualTo(String value) {
            addCriterion("DWZGBMBM <=", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmLike(String value) {
            addCriterion("DWZGBMBM like", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmNotLike(String value) {
            addCriterion("DWZGBMBM not like", value, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmIn(List<String> values) {
            addCriterion("DWZGBMBM in", values, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmNotIn(List<String> values) {
            addCriterion("DWZGBMBM not in", values, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmBetween(String value1, String value2) {
            addCriterion("DWZGBMBM between", value1, value2, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmbmNotBetween(String value1, String value2) {
            addCriterion("DWZGBMBM not between", value1, value2, "dwzgbmbm");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcIsNull() {
            addCriterion("DWZGBMMC is null");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcIsNotNull() {
            addCriterion("DWZGBMMC is not null");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcEqualTo(String value) {
            addCriterion("DWZGBMMC =", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcNotEqualTo(String value) {
            addCriterion("DWZGBMMC <>", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcGreaterThan(String value) {
            addCriterion("DWZGBMMC >", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcGreaterThanOrEqualTo(String value) {
            addCriterion("DWZGBMMC >=", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcLessThan(String value) {
            addCriterion("DWZGBMMC <", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcLessThanOrEqualTo(String value) {
            addCriterion("DWZGBMMC <=", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcLike(String value) {
            addCriterion("DWZGBMMC like", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcNotLike(String value) {
            addCriterion("DWZGBMMC not like", value, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcIn(List<String> values) {
            addCriterion("DWZGBMMC in", values, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcNotIn(List<String> values) {
            addCriterion("DWZGBMMC not in", values, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcBetween(String value1, String value2) {
            addCriterion("DWZGBMMC between", value1, value2, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andDwzgbmmcNotBetween(String value1, String value2) {
            addCriterion("DWZGBMMC not between", value1, value2, "dwzgbmmc");
            return (Criteria) this;
        }

        public Criteria andHkrzhIsNull() {
            addCriterion("HKRZH is null");
            return (Criteria) this;
        }

        public Criteria andHkrzhIsNotNull() {
            addCriterion("HKRZH is not null");
            return (Criteria) this;
        }

        public Criteria andHkrzhEqualTo(String value) {
            addCriterion("HKRZH =", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhNotEqualTo(String value) {
            addCriterion("HKRZH <>", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhGreaterThan(String value) {
            addCriterion("HKRZH >", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhGreaterThanOrEqualTo(String value) {
            addCriterion("HKRZH >=", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhLessThan(String value) {
            addCriterion("HKRZH <", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhLessThanOrEqualTo(String value) {
            addCriterion("HKRZH <=", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhLike(String value) {
            addCriterion("HKRZH like", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhNotLike(String value) {
            addCriterion("HKRZH not like", value, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhIn(List<String> values) {
            addCriterion("HKRZH in", values, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhNotIn(List<String> values) {
            addCriterion("HKRZH not in", values, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhBetween(String value1, String value2) {
            addCriterion("HKRZH between", value1, value2, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrzhNotBetween(String value1, String value2) {
            addCriterion("HKRZH not between", value1, value2, "hkrzh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhIsNull() {
            addCriterion("HKRKHYH is null");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhIsNotNull() {
            addCriterion("HKRKHYH is not null");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhEqualTo(String value) {
            addCriterion("HKRKHYH =", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhNotEqualTo(String value) {
            addCriterion("HKRKHYH <>", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhGreaterThan(String value) {
            addCriterion("HKRKHYH >", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhGreaterThanOrEqualTo(String value) {
            addCriterion("HKRKHYH >=", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhLessThan(String value) {
            addCriterion("HKRKHYH <", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhLessThanOrEqualTo(String value) {
            addCriterion("HKRKHYH <=", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhLike(String value) {
            addCriterion("HKRKHYH like", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhNotLike(String value) {
            addCriterion("HKRKHYH not like", value, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhIn(List<String> values) {
            addCriterion("HKRKHYH in", values, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhNotIn(List<String> values) {
            addCriterion("HKRKHYH not in", values, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhBetween(String value1, String value2) {
            addCriterion("HKRKHYH between", value1, value2, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andHkrkhyhNotBetween(String value1, String value2) {
            addCriterion("HKRKHYH not between", value1, value2, "hkrkhyh");
            return (Criteria) this;
        }

        public Criteria andYtIsNull() {
            addCriterion("YT is null");
            return (Criteria) this;
        }

        public Criteria andYtIsNotNull() {
            addCriterion("YT is not null");
            return (Criteria) this;
        }

        public Criteria andYtEqualTo(String value) {
            addCriterion("YT =", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotEqualTo(String value) {
            addCriterion("YT <>", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtGreaterThan(String value) {
            addCriterion("YT >", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtGreaterThanOrEqualTo(String value) {
            addCriterion("YT >=", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLessThan(String value) {
            addCriterion("YT <", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLessThanOrEqualTo(String value) {
            addCriterion("YT <=", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLike(String value) {
            addCriterion("YT like", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotLike(String value) {
            addCriterion("YT not like", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtIn(List<String> values) {
            addCriterion("YT in", values, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotIn(List<String> values) {
            addCriterion("YT not in", values, "yt");
            return (Criteria) this;
        }

        public Criteria andYtBetween(String value1, String value2) {
            addCriterion("YT between", value1, value2, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotBetween(String value1, String value2) {
            addCriterion("YT not between", value1, value2, "yt");
            return (Criteria) this;
        }

        public Criteria andFzqrxxIsNull() {
            addCriterion("FZQRXX is null");
            return (Criteria) this;
        }

        public Criteria andFzqrxxIsNotNull() {
            addCriterion("FZQRXX is not null");
            return (Criteria) this;
        }

        public Criteria andFzqrxxEqualTo(String value) {
            addCriterion("FZQRXX =", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxNotEqualTo(String value) {
            addCriterion("FZQRXX <>", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxGreaterThan(String value) {
            addCriterion("FZQRXX >", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxGreaterThanOrEqualTo(String value) {
            addCriterion("FZQRXX >=", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxLessThan(String value) {
            addCriterion("FZQRXX <", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxLessThanOrEqualTo(String value) {
            addCriterion("FZQRXX <=", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxLike(String value) {
            addCriterion("FZQRXX like", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxNotLike(String value) {
            addCriterion("FZQRXX not like", value, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxIn(List<String> values) {
            addCriterion("FZQRXX in", values, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxNotIn(List<String> values) {
            addCriterion("FZQRXX not in", values, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxBetween(String value1, String value2) {
            addCriterion("FZQRXX between", value1, value2, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andFzqrxxNotBetween(String value1, String value2) {
            addCriterion("FZQRXX not between", value1, value2, "fzqrxx");
            return (Criteria) this;
        }

        public Criteria andBmkywxhIsNull() {
            addCriterion("BMKYWXH is null");
            return (Criteria) this;
        }

        public Criteria andBmkywxhIsNotNull() {
            addCriterion("BMKYWXH is not null");
            return (Criteria) this;
        }

        public Criteria andBmkywxhEqualTo(String value) {
            addCriterion("BMKYWXH =", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotEqualTo(String value) {
            addCriterion("BMKYWXH <>", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhGreaterThan(String value) {
            addCriterion("BMKYWXH >", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhGreaterThanOrEqualTo(String value) {
            addCriterion("BMKYWXH >=", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhLessThan(String value) {
            addCriterion("BMKYWXH <", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhLessThanOrEqualTo(String value) {
            addCriterion("BMKYWXH <=", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhLike(String value) {
            addCriterion("BMKYWXH like", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotLike(String value) {
            addCriterion("BMKYWXH not like", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhIn(List<String> values) {
            addCriterion("BMKYWXH in", values, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotIn(List<String> values) {
            addCriterion("BMKYWXH not in", values, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhBetween(String value1, String value2) {
            addCriterion("BMKYWXH between", value1, value2, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotBetween(String value1, String value2) {
            addCriterion("BMKYWXH not between", value1, value2, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andJyrqIsNull() {
            addCriterion("JYRQ is null");
            return (Criteria) this;
        }

        public Criteria andJyrqIsNotNull() {
            addCriterion("JYRQ is not null");
            return (Criteria) this;
        }

        public Criteria andJyrqEqualTo(String value) {
            addCriterion("JYRQ =", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotEqualTo(String value) {
            addCriterion("JYRQ <>", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqGreaterThan(String value) {
            addCriterion("JYRQ >", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqGreaterThanOrEqualTo(String value) {
            addCriterion("JYRQ >=", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqLessThan(String value) {
            addCriterion("JYRQ <", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqLessThanOrEqualTo(String value) {
            addCriterion("JYRQ <=", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqLike(String value) {
            addCriterion("JYRQ like", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotLike(String value) {
            addCriterion("JYRQ not like", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqIn(List<String> values) {
            addCriterion("JYRQ in", values, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotIn(List<String> values) {
            addCriterion("JYRQ not in", values, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqBetween(String value1, String value2) {
            addCriterion("JYRQ between", value1, value2, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotBetween(String value1, String value2) {
            addCriterion("JYRQ not between", value1, value2, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJeIsNull() {
            addCriterion("JE is null");
            return (Criteria) this;
        }

        public Criteria andJeIsNotNull() {
            addCriterion("JE is not null");
            return (Criteria) this;
        }

        public Criteria andJeEqualTo(BigDecimal value) {
            addCriterion("JE =", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotEqualTo(BigDecimal value) {
            addCriterion("JE <>", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThan(BigDecimal value) {
            addCriterion("JE >", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JE >=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThan(BigDecimal value) {
            addCriterion("JE <", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JE <=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeIn(List<BigDecimal> values) {
            addCriterion("JE in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotIn(List<BigDecimal> values) {
            addCriterion("JE not in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE not between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNull() {
            addCriterion("BYZD1 is null");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNotNull() {
            addCriterion("BYZD1 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd1EqualTo(String value) {
            addCriterion("BYZD1 =", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotEqualTo(String value) {
            addCriterion("BYZD1 <>", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThan(String value) {
            addCriterion("BYZD1 >", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD1 >=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThan(String value) {
            addCriterion("BYZD1 <", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThanOrEqualTo(String value) {
            addCriterion("BYZD1 <=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Like(String value) {
            addCriterion("BYZD1 like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotLike(String value) {
            addCriterion("BYZD1 not like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1In(List<String> values) {
            addCriterion("BYZD1 in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotIn(List<String> values) {
            addCriterion("BYZD1 not in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Between(String value1, String value2) {
            addCriterion("BYZD1 between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotBetween(String value1, String value2) {
            addCriterion("BYZD1 not between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNull() {
            addCriterion("BYZD2 is null");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNotNull() {
            addCriterion("BYZD2 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd2EqualTo(String value) {
            addCriterion("BYZD2 =", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotEqualTo(String value) {
            addCriterion("BYZD2 <>", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThan(String value) {
            addCriterion("BYZD2 >", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD2 >=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThan(String value) {
            addCriterion("BYZD2 <", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThanOrEqualTo(String value) {
            addCriterion("BYZD2 <=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Like(String value) {
            addCriterion("BYZD2 like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotLike(String value) {
            addCriterion("BYZD2 not like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2In(List<String> values) {
            addCriterion("BYZD2 in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotIn(List<String> values) {
            addCriterion("BYZD2 not in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Between(String value1, String value2) {
            addCriterion("BYZD2 between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotBetween(String value1, String value2) {
            addCriterion("BYZD2 not between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNull() {
            addCriterion("BYZD3 is null");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNotNull() {
            addCriterion("BYZD3 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd3EqualTo(String value) {
            addCriterion("BYZD3 =", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotEqualTo(String value) {
            addCriterion("BYZD3 <>", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThan(String value) {
            addCriterion("BYZD3 >", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD3 >=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThan(String value) {
            addCriterion("BYZD3 <", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThanOrEqualTo(String value) {
            addCriterion("BYZD3 <=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Like(String value) {
            addCriterion("BYZD3 like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotLike(String value) {
            addCriterion("BYZD3 not like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3In(List<String> values) {
            addCriterion("BYZD3 in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotIn(List<String> values) {
            addCriterion("BYZD3 not in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Between(String value1, String value2) {
            addCriterion("BYZD3 between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotBetween(String value1, String value2) {
            addCriterion("BYZD3 not between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd4IsNull() {
            addCriterion("BYZD4 is null");
            return (Criteria) this;
        }

        public Criteria andByzd4IsNotNull() {
            addCriterion("BYZD4 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd4EqualTo(String value) {
            addCriterion("BYZD4 =", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotEqualTo(String value) {
            addCriterion("BYZD4 <>", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4GreaterThan(String value) {
            addCriterion("BYZD4 >", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD4 >=", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4LessThan(String value) {
            addCriterion("BYZD4 <", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4LessThanOrEqualTo(String value) {
            addCriterion("BYZD4 <=", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4Like(String value) {
            addCriterion("BYZD4 like", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotLike(String value) {
            addCriterion("BYZD4 not like", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4In(List<String> values) {
            addCriterion("BYZD4 in", values, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotIn(List<String> values) {
            addCriterion("BYZD4 not in", values, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4Between(String value1, String value2) {
            addCriterion("BYZD4 between", value1, value2, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotBetween(String value1, String value2) {
            addCriterion("BYZD4 not between", value1, value2, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd5IsNull() {
            addCriterion("BYZD5 is null");
            return (Criteria) this;
        }

        public Criteria andByzd5IsNotNull() {
            addCriterion("BYZD5 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd5EqualTo(String value) {
            addCriterion("BYZD5 =", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotEqualTo(String value) {
            addCriterion("BYZD5 <>", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5GreaterThan(String value) {
            addCriterion("BYZD5 >", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD5 >=", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5LessThan(String value) {
            addCriterion("BYZD5 <", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5LessThanOrEqualTo(String value) {
            addCriterion("BYZD5 <=", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5Like(String value) {
            addCriterion("BYZD5 like", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotLike(String value) {
            addCriterion("BYZD5 not like", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5In(List<String> values) {
            addCriterion("BYZD5 in", values, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotIn(List<String> values) {
            addCriterion("BYZD5 not in", values, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5Between(String value1, String value2) {
            addCriterion("BYZD5 between", value1, value2, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotBetween(String value1, String value2) {
            addCriterion("BYZD5 not between", value1, value2, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd6IsNull() {
            addCriterion("BYZD6 is null");
            return (Criteria) this;
        }

        public Criteria andByzd6IsNotNull() {
            addCriterion("BYZD6 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd6EqualTo(String value) {
            addCriterion("BYZD6 =", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotEqualTo(String value) {
            addCriterion("BYZD6 <>", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6GreaterThan(String value) {
            addCriterion("BYZD6 >", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD6 >=", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6LessThan(String value) {
            addCriterion("BYZD6 <", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6LessThanOrEqualTo(String value) {
            addCriterion("BYZD6 <=", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6Like(String value) {
            addCriterion("BYZD6 like", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotLike(String value) {
            addCriterion("BYZD6 not like", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6In(List<String> values) {
            addCriterion("BYZD6 in", values, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotIn(List<String> values) {
            addCriterion("BYZD6 not in", values, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6Between(String value1, String value2) {
            addCriterion("BYZD6 between", value1, value2, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotBetween(String value1, String value2) {
            addCriterion("BYZD6 not between", value1, value2, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd7IsNull() {
            addCriterion("BYZD7 is null");
            return (Criteria) this;
        }

        public Criteria andByzd7IsNotNull() {
            addCriterion("BYZD7 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd7EqualTo(String value) {
            addCriterion("BYZD7 =", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotEqualTo(String value) {
            addCriterion("BYZD7 <>", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7GreaterThan(String value) {
            addCriterion("BYZD7 >", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD7 >=", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7LessThan(String value) {
            addCriterion("BYZD7 <", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7LessThanOrEqualTo(String value) {
            addCriterion("BYZD7 <=", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7Like(String value) {
            addCriterion("BYZD7 like", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotLike(String value) {
            addCriterion("BYZD7 not like", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7In(List<String> values) {
            addCriterion("BYZD7 in", values, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotIn(List<String> values) {
            addCriterion("BYZD7 not in", values, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7Between(String value1, String value2) {
            addCriterion("BYZD7 between", value1, value2, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotBetween(String value1, String value2) {
            addCriterion("BYZD7 not between", value1, value2, "byzd7");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(String value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(String value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(String value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(String value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(String value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLike(String value) {
            addCriterion("OPER_DATE like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotLike(String value) {
            addCriterion("OPER_DATE not like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<String> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<String> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(String value1, String value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(String value1, String value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(String value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(String value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(String value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(String value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLike(String value) {
            addCriterion("OPER_TIME like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotLike(String value) {
            addCriterion("OPER_TIME not like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<String> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<String> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(String value1, String value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(String value1, String value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagIsNull() {
            addCriterion("QDF_CFM_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagIsNotNull() {
            addCriterion("QDF_CFM_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagEqualTo(String value) {
            addCriterion("QDF_CFM_FLAG =", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagNotEqualTo(String value) {
            addCriterion("QDF_CFM_FLAG <>", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagGreaterThan(String value) {
            addCriterion("QDF_CFM_FLAG >", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagGreaterThanOrEqualTo(String value) {
            addCriterion("QDF_CFM_FLAG >=", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagLessThan(String value) {
            addCriterion("QDF_CFM_FLAG <", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagLessThanOrEqualTo(String value) {
            addCriterion("QDF_CFM_FLAG <=", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagLike(String value) {
            addCriterion("QDF_CFM_FLAG like", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagNotLike(String value) {
            addCriterion("QDF_CFM_FLAG not like", value, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagIn(List<String> values) {
            addCriterion("QDF_CFM_FLAG in", values, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagNotIn(List<String> values) {
            addCriterion("QDF_CFM_FLAG not in", values, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagBetween(String value1, String value2) {
            addCriterion("QDF_CFM_FLAG between", value1, value2, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmFlagNotBetween(String value1, String value2) {
            addCriterion("QDF_CFM_FLAG not between", value1, value2, "qdfCfmFlag");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgIsNull() {
            addCriterion("QDF_CFM_MSG is null");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgIsNotNull() {
            addCriterion("QDF_CFM_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgEqualTo(String value) {
            addCriterion("QDF_CFM_MSG =", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgNotEqualTo(String value) {
            addCriterion("QDF_CFM_MSG <>", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgGreaterThan(String value) {
            addCriterion("QDF_CFM_MSG >", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgGreaterThanOrEqualTo(String value) {
            addCriterion("QDF_CFM_MSG >=", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgLessThan(String value) {
            addCriterion("QDF_CFM_MSG <", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgLessThanOrEqualTo(String value) {
            addCriterion("QDF_CFM_MSG <=", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgLike(String value) {
            addCriterion("QDF_CFM_MSG like", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgNotLike(String value) {
            addCriterion("QDF_CFM_MSG not like", value, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgIn(List<String> values) {
            addCriterion("QDF_CFM_MSG in", values, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgNotIn(List<String> values) {
            addCriterion("QDF_CFM_MSG not in", values, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgBetween(String value1, String value2) {
            addCriterion("QDF_CFM_MSG between", value1, value2, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andQdfCfmMsgNotBetween(String value1, String value2) {
            addCriterion("QDF_CFM_MSG not between", value1, value2, "qdfCfmMsg");
            return (Criteria) this;
        }

        public Criteria andZsdwmcIsNull() {
            addCriterion("ZSDWMC is null");
            return (Criteria) this;
        }

        public Criteria andZsdwmcIsNotNull() {
            addCriterion("ZSDWMC is not null");
            return (Criteria) this;
        }

        public Criteria andZsdwmcEqualTo(String value) {
            addCriterion("ZSDWMC =", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcNotEqualTo(String value) {
            addCriterion("ZSDWMC <>", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcGreaterThan(String value) {
            addCriterion("ZSDWMC >", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcGreaterThanOrEqualTo(String value) {
            addCriterion("ZSDWMC >=", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcLessThan(String value) {
            addCriterion("ZSDWMC <", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcLessThanOrEqualTo(String value) {
            addCriterion("ZSDWMC <=", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcLike(String value) {
            addCriterion("ZSDWMC like", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcNotLike(String value) {
            addCriterion("ZSDWMC not like", value, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcIn(List<String> values) {
            addCriterion("ZSDWMC in", values, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcNotIn(List<String> values) {
            addCriterion("ZSDWMC not in", values, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcBetween(String value1, String value2) {
            addCriterion("ZSDWMC between", value1, value2, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andZsdwmcNotBetween(String value1, String value2) {
            addCriterion("ZSDWMC not between", value1, value2, "zsdwmc");
            return (Criteria) this;
        }

        public Criteria andChkFlagIsNull() {
            addCriterion("CHK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andChkFlagIsNotNull() {
            addCriterion("CHK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andChkFlagEqualTo(String value) {
            addCriterion("CHK_FLAG =", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotEqualTo(String value) {
            addCriterion("CHK_FLAG <>", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagGreaterThan(String value) {
            addCriterion("CHK_FLAG >", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_FLAG >=", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagLessThan(String value) {
            addCriterion("CHK_FLAG <", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagLessThanOrEqualTo(String value) {
            addCriterion("CHK_FLAG <=", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagLike(String value) {
            addCriterion("CHK_FLAG like", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotLike(String value) {
            addCriterion("CHK_FLAG not like", value, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagIn(List<String> values) {
            addCriterion("CHK_FLAG in", values, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotIn(List<String> values) {
            addCriterion("CHK_FLAG not in", values, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagBetween(String value1, String value2) {
            addCriterion("CHK_FLAG between", value1, value2, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andChkFlagNotBetween(String value1, String value2) {
            addCriterion("CHK_FLAG not between", value1, value2, "chkFlag");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNull() {
            addCriterion("ADD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andAddDateIsNotNull() {
            addCriterion("ADD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andAddDateEqualTo(String value) {
            addCriterion("ADD_DATE =", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotEqualTo(String value) {
            addCriterion("ADD_DATE <>", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThan(String value) {
            addCriterion("ADD_DATE >", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateGreaterThanOrEqualTo(String value) {
            addCriterion("ADD_DATE >=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThan(String value) {
            addCriterion("ADD_DATE <", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLessThanOrEqualTo(String value) {
            addCriterion("ADD_DATE <=", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateLike(String value) {
            addCriterion("ADD_DATE like", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotLike(String value) {
            addCriterion("ADD_DATE not like", value, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateIn(List<String> values) {
            addCriterion("ADD_DATE in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotIn(List<String> values) {
            addCriterion("ADD_DATE not in", values, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateBetween(String value1, String value2) {
            addCriterion("ADD_DATE between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andAddDateNotBetween(String value1, String value2) {
            addCriterion("ADD_DATE not between", value1, value2, "addDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateIsNull() {
            addCriterion("CONFIRM_DATE is null");
            return (Criteria) this;
        }

        public Criteria andConfirmDateIsNotNull() {
            addCriterion("CONFIRM_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmDateEqualTo(String value) {
            addCriterion("CONFIRM_DATE =", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateNotEqualTo(String value) {
            addCriterion("CONFIRM_DATE <>", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateGreaterThan(String value) {
            addCriterion("CONFIRM_DATE >", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateGreaterThanOrEqualTo(String value) {
            addCriterion("CONFIRM_DATE >=", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateLessThan(String value) {
            addCriterion("CONFIRM_DATE <", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateLessThanOrEqualTo(String value) {
            addCriterion("CONFIRM_DATE <=", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateLike(String value) {
            addCriterion("CONFIRM_DATE like", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateNotLike(String value) {
            addCriterion("CONFIRM_DATE not like", value, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateIn(List<String> values) {
            addCriterion("CONFIRM_DATE in", values, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateNotIn(List<String> values) {
            addCriterion("CONFIRM_DATE not in", values, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateBetween(String value1, String value2) {
            addCriterion("CONFIRM_DATE between", value1, value2, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andConfirmDateNotBetween(String value1, String value2) {
            addCriterion("CONFIRM_DATE not between", value1, value2, "confirmDate");
            return (Criteria) this;
        }

        public Criteria andChkDateIsNull() {
            addCriterion("CHK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andChkDateIsNotNull() {
            addCriterion("CHK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andChkDateEqualTo(String value) {
            addCriterion("CHK_DATE =", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotEqualTo(String value) {
            addCriterion("CHK_DATE <>", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateGreaterThan(String value) {
            addCriterion("CHK_DATE >", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_DATE >=", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateLessThan(String value) {
            addCriterion("CHK_DATE <", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateLessThanOrEqualTo(String value) {
            addCriterion("CHK_DATE <=", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateLike(String value) {
            addCriterion("CHK_DATE like", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotLike(String value) {
            addCriterion("CHK_DATE not like", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateIn(List<String> values) {
            addCriterion("CHK_DATE in", values, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotIn(List<String> values) {
            addCriterion("CHK_DATE not in", values, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateBetween(String value1, String value2) {
            addCriterion("CHK_DATE between", value1, value2, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotBetween(String value1, String value2) {
            addCriterion("CHK_DATE not between", value1, value2, "chkDate");
            return (Criteria) this;
        }

        public Criteria andJkfsIsNull() {
            addCriterion("JKFS is null");
            return (Criteria) this;
        }

        public Criteria andJkfsIsNotNull() {
            addCriterion("JKFS is not null");
            return (Criteria) this;
        }

        public Criteria andJkfsEqualTo(String value) {
            addCriterion("JKFS =", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotEqualTo(String value) {
            addCriterion("JKFS <>", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsGreaterThan(String value) {
            addCriterion("JKFS >", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsGreaterThanOrEqualTo(String value) {
            addCriterion("JKFS >=", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLessThan(String value) {
            addCriterion("JKFS <", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLessThanOrEqualTo(String value) {
            addCriterion("JKFS <=", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLike(String value) {
            addCriterion("JKFS like", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotLike(String value) {
            addCriterion("JKFS not like", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsIn(List<String> values) {
            addCriterion("JKFS in", values, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotIn(List<String> values) {
            addCriterion("JKFS not in", values, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsBetween(String value1, String value2) {
            addCriterion("JKFS between", value1, value2, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotBetween(String value1, String value2) {
            addCriterion("JKFS not between", value1, value2, "jkfs");
            return (Criteria) this;
        }

        public Criteria andHkrqcIsNull() {
            addCriterion("HKRQC is null");
            return (Criteria) this;
        }

        public Criteria andHkrqcIsNotNull() {
            addCriterion("HKRQC is not null");
            return (Criteria) this;
        }

        public Criteria andHkrqcEqualTo(String value) {
            addCriterion("HKRQC =", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcNotEqualTo(String value) {
            addCriterion("HKRQC <>", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcGreaterThan(String value) {
            addCriterion("HKRQC >", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcGreaterThanOrEqualTo(String value) {
            addCriterion("HKRQC >=", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcLessThan(String value) {
            addCriterion("HKRQC <", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcLessThanOrEqualTo(String value) {
            addCriterion("HKRQC <=", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcLike(String value) {
            addCriterion("HKRQC like", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcNotLike(String value) {
            addCriterion("HKRQC not like", value, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcIn(List<String> values) {
            addCriterion("HKRQC in", values, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcNotIn(List<String> values) {
            addCriterion("HKRQC not in", values, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcBetween(String value1, String value2) {
            addCriterion("HKRQC between", value1, value2, "hkrqc");
            return (Criteria) this;
        }

        public Criteria andHkrqcNotBetween(String value1, String value2) {
            addCriterion("HKRQC not between", value1, value2, "hkrqc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 08 21:54:06 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Mon Jul 08 21:54:06 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}