package fnt.repository.model;

import java.math.BigDecimal;

public class FsQdfPendingTxn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.PKID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.XZQH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String xzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BMKYWXH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String bmkywxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.CZZHZH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String czzhzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.JKFS
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String jkfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.YT
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String yt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.JE
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private BigDecimal je;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.JYRQ
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String jyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.TXAC_BRID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String txacBrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BOOK_OPERID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String bookOperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.OPER_TIME
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD1
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD2
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD3
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD4
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD5
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD6
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PENDING_TXN.BYZD7
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    private String byzd7;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.PKID
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.PKID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.PKID
     *
     * @param pkid the value for FIS.FS_QDF_PENDING_TXN.PKID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.XZQH
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.XZQH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.XZQH
     *
     * @param xzqh the value for FIS.FS_QDF_PENDING_TXN.XZQH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BMKYWXH
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BMKYWXH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getBmkywxh() {
        return bmkywxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BMKYWXH
     *
     * @param bmkywxh the value for FIS.FS_QDF_PENDING_TXN.BMKYWXH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setBmkywxh(String bmkywxh) {
        this.bmkywxh = bmkywxh == null ? null : bmkywxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.CZZHZH
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.CZZHZH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getCzzhzh() {
        return czzhzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.CZZHZH
     *
     * @param czzhzh the value for FIS.FS_QDF_PENDING_TXN.CZZHZH
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setCzzhzh(String czzhzh) {
        this.czzhzh = czzhzh == null ? null : czzhzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.JKFS
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.JKFS
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getJkfs() {
        return jkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.JKFS
     *
     * @param jkfs the value for FIS.FS_QDF_PENDING_TXN.JKFS
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setJkfs(String jkfs) {
        this.jkfs = jkfs == null ? null : jkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.YT
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.YT
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getYt() {
        return yt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.YT
     *
     * @param yt the value for FIS.FS_QDF_PENDING_TXN.YT
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setYt(String yt) {
        this.yt = yt == null ? null : yt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.JE
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.JE
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public BigDecimal getJe() {
        return je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.JE
     *
     * @param je the value for FIS.FS_QDF_PENDING_TXN.JE
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setJe(BigDecimal je) {
        this.je = je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.JYRQ
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.JYRQ
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getJyrq() {
        return jyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.JYRQ
     *
     * @param jyrq the value for FIS.FS_QDF_PENDING_TXN.JYRQ
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setJyrq(String jyrq) {
        this.jyrq = jyrq == null ? null : jyrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.TXAC_BRID
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.TXAC_BRID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getTxacBrid() {
        return txacBrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.TXAC_BRID
     *
     * @param txacBrid the value for FIS.FS_QDF_PENDING_TXN.TXAC_BRID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setTxacBrid(String txacBrid) {
        this.txacBrid = txacBrid == null ? null : txacBrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BOOK_OPERID
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BOOK_OPERID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getBookOperid() {
        return bookOperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BOOK_OPERID
     *
     * @param bookOperid the value for FIS.FS_QDF_PENDING_TXN.BOOK_OPERID
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setBookOperid(String bookOperid) {
        this.bookOperid = bookOperid == null ? null : bookOperid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.OPER_TIME
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.OPER_TIME
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.OPER_TIME
     *
     * @param operTime the value for FIS.FS_QDF_PENDING_TXN.OPER_TIME
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD1
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD1
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd1() {
        return byzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD1
     *
     * @param byzd1 the value for FIS.FS_QDF_PENDING_TXN.BYZD1
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd1(String byzd1) {
        this.byzd1 = byzd1 == null ? null : byzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD2
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD2
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd2() {
        return byzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD2
     *
     * @param byzd2 the value for FIS.FS_QDF_PENDING_TXN.BYZD2
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd2(String byzd2) {
        this.byzd2 = byzd2 == null ? null : byzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD3
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD3
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd3() {
        return byzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD3
     *
     * @param byzd3 the value for FIS.FS_QDF_PENDING_TXN.BYZD3
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd3(String byzd3) {
        this.byzd3 = byzd3 == null ? null : byzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD4
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD4
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd4() {
        return byzd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD4
     *
     * @param byzd4 the value for FIS.FS_QDF_PENDING_TXN.BYZD4
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd4(String byzd4) {
        this.byzd4 = byzd4 == null ? null : byzd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD5
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD5
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd5() {
        return byzd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD5
     *
     * @param byzd5 the value for FIS.FS_QDF_PENDING_TXN.BYZD5
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd5(String byzd5) {
        this.byzd5 = byzd5 == null ? null : byzd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD6
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD6
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd6() {
        return byzd6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD6
     *
     * @param byzd6 the value for FIS.FS_QDF_PENDING_TXN.BYZD6
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd6(String byzd6) {
        this.byzd6 = byzd6 == null ? null : byzd6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD7
     *
     * @return the value of FIS.FS_QDF_PENDING_TXN.BYZD7
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getByzd7() {
        return byzd7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PENDING_TXN.BYZD7
     *
     * @param byzd7 the value for FIS.FS_QDF_PENDING_TXN.BYZD7
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setByzd7(String byzd7) {
        this.byzd7 = byzd7 == null ? null : byzd7.trim();
    }
}