package fnt.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FsQdfChkVchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public FsQdfChkVchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPjzlIsNull() {
            addCriterion("PJZL is null");
            return (Criteria) this;
        }

        public Criteria andPjzlIsNotNull() {
            addCriterion("PJZL is not null");
            return (Criteria) this;
        }

        public Criteria andPjzlEqualTo(String value) {
            addCriterion("PJZL =", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotEqualTo(String value) {
            addCriterion("PJZL <>", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlGreaterThan(String value) {
            addCriterion("PJZL >", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlGreaterThanOrEqualTo(String value) {
            addCriterion("PJZL >=", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlLessThan(String value) {
            addCriterion("PJZL <", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlLessThanOrEqualTo(String value) {
            addCriterion("PJZL <=", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlLike(String value) {
            addCriterion("PJZL like", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotLike(String value) {
            addCriterion("PJZL not like", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlIn(List<String> values) {
            addCriterion("PJZL in", values, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotIn(List<String> values) {
            addCriterion("PJZL not in", values, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlBetween(String value1, String value2) {
            addCriterion("PJZL between", value1, value2, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotBetween(String value1, String value2) {
            addCriterion("PJZL not between", value1, value2, "pjzl");
            return (Criteria) this;
        }

        public Criteria andJksbhIsNull() {
            addCriterion("JKSBH is null");
            return (Criteria) this;
        }

        public Criteria andJksbhIsNotNull() {
            addCriterion("JKSBH is not null");
            return (Criteria) this;
        }

        public Criteria andJksbhEqualTo(String value) {
            addCriterion("JKSBH =", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotEqualTo(String value) {
            addCriterion("JKSBH <>", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhGreaterThan(String value) {
            addCriterion("JKSBH >", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhGreaterThanOrEqualTo(String value) {
            addCriterion("JKSBH >=", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhLessThan(String value) {
            addCriterion("JKSBH <", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhLessThanOrEqualTo(String value) {
            addCriterion("JKSBH <=", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhLike(String value) {
            addCriterion("JKSBH like", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotLike(String value) {
            addCriterion("JKSBH not like", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhIn(List<String> values) {
            addCriterion("JKSBH in", values, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotIn(List<String> values) {
            addCriterion("JKSBH not in", values, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhBetween(String value1, String value2) {
            addCriterion("JKSBH between", value1, value2, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotBetween(String value1, String value2) {
            addCriterion("JKSBH not between", value1, value2, "jksbh");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmIsNull() {
            addCriterion("WTZSDWBM is null");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmIsNotNull() {
            addCriterion("WTZSDWBM is not null");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmEqualTo(String value) {
            addCriterion("WTZSDWBM =", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmNotEqualTo(String value) {
            addCriterion("WTZSDWBM <>", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmGreaterThan(String value) {
            addCriterion("WTZSDWBM >", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmGreaterThanOrEqualTo(String value) {
            addCriterion("WTZSDWBM >=", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmLessThan(String value) {
            addCriterion("WTZSDWBM <", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmLessThanOrEqualTo(String value) {
            addCriterion("WTZSDWBM <=", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmLike(String value) {
            addCriterion("WTZSDWBM like", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmNotLike(String value) {
            addCriterion("WTZSDWBM not like", value, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmIn(List<String> values) {
            addCriterion("WTZSDWBM in", values, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmNotIn(List<String> values) {
            addCriterion("WTZSDWBM not in", values, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmBetween(String value1, String value2) {
            addCriterion("WTZSDWBM between", value1, value2, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andWtzsdwbmNotBetween(String value1, String value2) {
            addCriterion("WTZSDWBM not between", value1, value2, "wtzsdwbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmIsNull() {
            addCriterion("SRXMBM is null");
            return (Criteria) this;
        }

        public Criteria andSrxmbmIsNotNull() {
            addCriterion("SRXMBM is not null");
            return (Criteria) this;
        }

        public Criteria andSrxmbmEqualTo(String value) {
            addCriterion("SRXMBM =", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotEqualTo(String value) {
            addCriterion("SRXMBM <>", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmGreaterThan(String value) {
            addCriterion("SRXMBM >", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmGreaterThanOrEqualTo(String value) {
            addCriterion("SRXMBM >=", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmLessThan(String value) {
            addCriterion("SRXMBM <", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmLessThanOrEqualTo(String value) {
            addCriterion("SRXMBM <=", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmLike(String value) {
            addCriterion("SRXMBM like", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotLike(String value) {
            addCriterion("SRXMBM not like", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmIn(List<String> values) {
            addCriterion("SRXMBM in", values, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotIn(List<String> values) {
            addCriterion("SRXMBM not in", values, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmBetween(String value1, String value2) {
            addCriterion("SRXMBM between", value1, value2, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotBetween(String value1, String value2) {
            addCriterion("SRXMBM not between", value1, value2, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSlIsNull() {
            addCriterion("SL is null");
            return (Criteria) this;
        }

        public Criteria andSlIsNotNull() {
            addCriterion("SL is not null");
            return (Criteria) this;
        }

        public Criteria andSlEqualTo(BigDecimal value) {
            addCriterion("SL =", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotEqualTo(BigDecimal value) {
            addCriterion("SL <>", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThan(BigDecimal value) {
            addCriterion("SL >", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SL >=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThan(BigDecimal value) {
            addCriterion("SL <", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SL <=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlIn(List<BigDecimal> values) {
            addCriterion("SL in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotIn(List<BigDecimal> values) {
            addCriterion("SL not in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SL between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SL not between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andJeIsNull() {
            addCriterion("JE is null");
            return (Criteria) this;
        }

        public Criteria andJeIsNotNull() {
            addCriterion("JE is not null");
            return (Criteria) this;
        }

        public Criteria andJeEqualTo(BigDecimal value) {
            addCriterion("JE =", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotEqualTo(BigDecimal value) {
            addCriterion("JE <>", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThan(BigDecimal value) {
            addCriterion("JE >", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JE >=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThan(BigDecimal value) {
            addCriterion("JE <", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JE <=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeIn(List<BigDecimal> values) {
            addCriterion("JE in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotIn(List<BigDecimal> values) {
            addCriterion("JE not in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE not between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andYhskrqIsNull() {
            addCriterion("YHSKRQ is null");
            return (Criteria) this;
        }

        public Criteria andYhskrqIsNotNull() {
            addCriterion("YHSKRQ is not null");
            return (Criteria) this;
        }

        public Criteria andYhskrqEqualTo(String value) {
            addCriterion("YHSKRQ =", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqNotEqualTo(String value) {
            addCriterion("YHSKRQ <>", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqGreaterThan(String value) {
            addCriterion("YHSKRQ >", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqGreaterThanOrEqualTo(String value) {
            addCriterion("YHSKRQ >=", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqLessThan(String value) {
            addCriterion("YHSKRQ <", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqLessThanOrEqualTo(String value) {
            addCriterion("YHSKRQ <=", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqLike(String value) {
            addCriterion("YHSKRQ like", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqNotLike(String value) {
            addCriterion("YHSKRQ not like", value, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqIn(List<String> values) {
            addCriterion("YHSKRQ in", values, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqNotIn(List<String> values) {
            addCriterion("YHSKRQ not in", values, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqBetween(String value1, String value2) {
            addCriterion("YHSKRQ between", value1, value2, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andYhskrqNotBetween(String value1, String value2) {
            addCriterion("YHSKRQ not between", value1, value2, "yhskrq");
            return (Criteria) this;
        }

        public Criteria andJkfsIsNull() {
            addCriterion("JKFS is null");
            return (Criteria) this;
        }

        public Criteria andJkfsIsNotNull() {
            addCriterion("JKFS is not null");
            return (Criteria) this;
        }

        public Criteria andJkfsEqualTo(String value) {
            addCriterion("JKFS =", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotEqualTo(String value) {
            addCriterion("JKFS <>", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsGreaterThan(String value) {
            addCriterion("JKFS >", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsGreaterThanOrEqualTo(String value) {
            addCriterion("JKFS >=", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLessThan(String value) {
            addCriterion("JKFS <", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLessThanOrEqualTo(String value) {
            addCriterion("JKFS <=", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLike(String value) {
            addCriterion("JKFS like", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotLike(String value) {
            addCriterion("JKFS not like", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsIn(List<String> values) {
            addCriterion("JKFS in", values, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotIn(List<String> values) {
            addCriterion("JKFS not in", values, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsBetween(String value1, String value2) {
            addCriterion("JKFS between", value1, value2, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotBetween(String value1, String value2) {
            addCriterion("JKFS not between", value1, value2, "jkfs");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNull() {
            addCriterion("BYZD1 is null");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNotNull() {
            addCriterion("BYZD1 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd1EqualTo(String value) {
            addCriterion("BYZD1 =", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotEqualTo(String value) {
            addCriterion("BYZD1 <>", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThan(String value) {
            addCriterion("BYZD1 >", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD1 >=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThan(String value) {
            addCriterion("BYZD1 <", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThanOrEqualTo(String value) {
            addCriterion("BYZD1 <=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Like(String value) {
            addCriterion("BYZD1 like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotLike(String value) {
            addCriterion("BYZD1 not like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1In(List<String> values) {
            addCriterion("BYZD1 in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotIn(List<String> values) {
            addCriterion("BYZD1 not in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Between(String value1, String value2) {
            addCriterion("BYZD1 between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotBetween(String value1, String value2) {
            addCriterion("BYZD1 not between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNull() {
            addCriterion("BYZD2 is null");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNotNull() {
            addCriterion("BYZD2 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd2EqualTo(String value) {
            addCriterion("BYZD2 =", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotEqualTo(String value) {
            addCriterion("BYZD2 <>", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThan(String value) {
            addCriterion("BYZD2 >", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD2 >=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThan(String value) {
            addCriterion("BYZD2 <", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThanOrEqualTo(String value) {
            addCriterion("BYZD2 <=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Like(String value) {
            addCriterion("BYZD2 like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotLike(String value) {
            addCriterion("BYZD2 not like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2In(List<String> values) {
            addCriterion("BYZD2 in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotIn(List<String> values) {
            addCriterion("BYZD2 not in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Between(String value1, String value2) {
            addCriterion("BYZD2 between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotBetween(String value1, String value2) {
            addCriterion("BYZD2 not between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNull() {
            addCriterion("BYZD3 is null");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNotNull() {
            addCriterion("BYZD3 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd3EqualTo(String value) {
            addCriterion("BYZD3 =", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotEqualTo(String value) {
            addCriterion("BYZD3 <>", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThan(String value) {
            addCriterion("BYZD3 >", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD3 >=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThan(String value) {
            addCriterion("BYZD3 <", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThanOrEqualTo(String value) {
            addCriterion("BYZD3 <=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Like(String value) {
            addCriterion("BYZD3 like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotLike(String value) {
            addCriterion("BYZD3 not like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3In(List<String> values) {
            addCriterion("BYZD3 in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotIn(List<String> values) {
            addCriterion("BYZD3 not in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Between(String value1, String value2) {
            addCriterion("BYZD3 between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotBetween(String value1, String value2) {
            addCriterion("BYZD3 not between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd4IsNull() {
            addCriterion("BYZD4 is null");
            return (Criteria) this;
        }

        public Criteria andByzd4IsNotNull() {
            addCriterion("BYZD4 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd4EqualTo(String value) {
            addCriterion("BYZD4 =", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotEqualTo(String value) {
            addCriterion("BYZD4 <>", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4GreaterThan(String value) {
            addCriterion("BYZD4 >", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD4 >=", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4LessThan(String value) {
            addCriterion("BYZD4 <", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4LessThanOrEqualTo(String value) {
            addCriterion("BYZD4 <=", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4Like(String value) {
            addCriterion("BYZD4 like", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotLike(String value) {
            addCriterion("BYZD4 not like", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4In(List<String> values) {
            addCriterion("BYZD4 in", values, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotIn(List<String> values) {
            addCriterion("BYZD4 not in", values, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4Between(String value1, String value2) {
            addCriterion("BYZD4 between", value1, value2, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotBetween(String value1, String value2) {
            addCriterion("BYZD4 not between", value1, value2, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd5IsNull() {
            addCriterion("BYZD5 is null");
            return (Criteria) this;
        }

        public Criteria andByzd5IsNotNull() {
            addCriterion("BYZD5 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd5EqualTo(String value) {
            addCriterion("BYZD5 =", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotEqualTo(String value) {
            addCriterion("BYZD5 <>", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5GreaterThan(String value) {
            addCriterion("BYZD5 >", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD5 >=", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5LessThan(String value) {
            addCriterion("BYZD5 <", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5LessThanOrEqualTo(String value) {
            addCriterion("BYZD5 <=", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5Like(String value) {
            addCriterion("BYZD5 like", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotLike(String value) {
            addCriterion("BYZD5 not like", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5In(List<String> values) {
            addCriterion("BYZD5 in", values, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotIn(List<String> values) {
            addCriterion("BYZD5 not in", values, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5Between(String value1, String value2) {
            addCriterion("BYZD5 between", value1, value2, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotBetween(String value1, String value2) {
            addCriterion("BYZD5 not between", value1, value2, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd6IsNull() {
            addCriterion("BYZD6 is null");
            return (Criteria) this;
        }

        public Criteria andByzd6IsNotNull() {
            addCriterion("BYZD6 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd6EqualTo(String value) {
            addCriterion("BYZD6 =", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotEqualTo(String value) {
            addCriterion("BYZD6 <>", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6GreaterThan(String value) {
            addCriterion("BYZD6 >", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD6 >=", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6LessThan(String value) {
            addCriterion("BYZD6 <", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6LessThanOrEqualTo(String value) {
            addCriterion("BYZD6 <=", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6Like(String value) {
            addCriterion("BYZD6 like", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotLike(String value) {
            addCriterion("BYZD6 not like", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6In(List<String> values) {
            addCriterion("BYZD6 in", values, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotIn(List<String> values) {
            addCriterion("BYZD6 not in", values, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6Between(String value1, String value2) {
            addCriterion("BYZD6 between", value1, value2, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotBetween(String value1, String value2) {
            addCriterion("BYZD6 not between", value1, value2, "byzd6");
            return (Criteria) this;
        }

        public Criteria andDzsbyyIsNull() {
            addCriterion("DZSBYY is null");
            return (Criteria) this;
        }

        public Criteria andDzsbyyIsNotNull() {
            addCriterion("DZSBYY is not null");
            return (Criteria) this;
        }

        public Criteria andDzsbyyEqualTo(String value) {
            addCriterion("DZSBYY =", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyNotEqualTo(String value) {
            addCriterion("DZSBYY <>", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyGreaterThan(String value) {
            addCriterion("DZSBYY >", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyGreaterThanOrEqualTo(String value) {
            addCriterion("DZSBYY >=", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyLessThan(String value) {
            addCriterion("DZSBYY <", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyLessThanOrEqualTo(String value) {
            addCriterion("DZSBYY <=", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyLike(String value) {
            addCriterion("DZSBYY like", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyNotLike(String value) {
            addCriterion("DZSBYY not like", value, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyIn(List<String> values) {
            addCriterion("DZSBYY in", values, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyNotIn(List<String> values) {
            addCriterion("DZSBYY not in", values, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyBetween(String value1, String value2) {
            addCriterion("DZSBYY between", value1, value2, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andDzsbyyNotBetween(String value1, String value2) {
            addCriterion("DZSBYY not between", value1, value2, "dzsbyy");
            return (Criteria) this;
        }

        public Criteria andChkStsIsNull() {
            addCriterion("CHK_STS is null");
            return (Criteria) this;
        }

        public Criteria andChkStsIsNotNull() {
            addCriterion("CHK_STS is not null");
            return (Criteria) this;
        }

        public Criteria andChkStsEqualTo(String value) {
            addCriterion("CHK_STS =", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotEqualTo(String value) {
            addCriterion("CHK_STS <>", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsGreaterThan(String value) {
            addCriterion("CHK_STS >", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_STS >=", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLessThan(String value) {
            addCriterion("CHK_STS <", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLessThanOrEqualTo(String value) {
            addCriterion("CHK_STS <=", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLike(String value) {
            addCriterion("CHK_STS like", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotLike(String value) {
            addCriterion("CHK_STS not like", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsIn(List<String> values) {
            addCriterion("CHK_STS in", values, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotIn(List<String> values) {
            addCriterion("CHK_STS not in", values, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsBetween(String value1, String value2) {
            addCriterion("CHK_STS between", value1, value2, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotBetween(String value1, String value2) {
            addCriterion("CHK_STS not between", value1, value2, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkDateIsNull() {
            addCriterion("CHK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andChkDateIsNotNull() {
            addCriterion("CHK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andChkDateEqualTo(String value) {
            addCriterion("CHK_DATE =", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotEqualTo(String value) {
            addCriterion("CHK_DATE <>", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateGreaterThan(String value) {
            addCriterion("CHK_DATE >", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_DATE >=", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateLessThan(String value) {
            addCriterion("CHK_DATE <", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateLessThanOrEqualTo(String value) {
            addCriterion("CHK_DATE <=", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateLike(String value) {
            addCriterion("CHK_DATE like", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotLike(String value) {
            addCriterion("CHK_DATE not like", value, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateIn(List<String> values) {
            addCriterion("CHK_DATE in", values, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotIn(List<String> values) {
            addCriterion("CHK_DATE not in", values, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateBetween(String value1, String value2) {
            addCriterion("CHK_DATE between", value1, value2, "chkDate");
            return (Criteria) this;
        }

        public Criteria andChkDateNotBetween(String value1, String value2) {
            addCriterion("CHK_DATE not between", value1, value2, "chkDate");
            return (Criteria) this;
        }

        public Criteria andDataSysIdIsNull() {
            addCriterion("DATA_SYS_ID is null");
            return (Criteria) this;
        }

        public Criteria andDataSysIdIsNotNull() {
            addCriterion("DATA_SYS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDataSysIdEqualTo(String value) {
            addCriterion("DATA_SYS_ID =", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdNotEqualTo(String value) {
            addCriterion("DATA_SYS_ID <>", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdGreaterThan(String value) {
            addCriterion("DATA_SYS_ID >", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_SYS_ID >=", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdLessThan(String value) {
            addCriterion("DATA_SYS_ID <", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdLessThanOrEqualTo(String value) {
            addCriterion("DATA_SYS_ID <=", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdLike(String value) {
            addCriterion("DATA_SYS_ID like", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdNotLike(String value) {
            addCriterion("DATA_SYS_ID not like", value, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdIn(List<String> values) {
            addCriterion("DATA_SYS_ID in", values, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdNotIn(List<String> values) {
            addCriterion("DATA_SYS_ID not in", values, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdBetween(String value1, String value2) {
            addCriterion("DATA_SYS_ID between", value1, value2, "dataSysId");
            return (Criteria) this;
        }

        public Criteria andDataSysIdNotBetween(String value1, String value2) {
            addCriterion("DATA_SYS_ID not between", value1, value2, "dataSysId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 24 11:41:37 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_CHK_VCH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}