package fnt.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FsQdfPaymentItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public FsQdfPaymentItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andXmsxIsNull() {
            addCriterion("XMSX is null");
            return (Criteria) this;
        }

        public Criteria andXmsxIsNotNull() {
            addCriterion("XMSX is not null");
            return (Criteria) this;
        }

        public Criteria andXmsxEqualTo(String value) {
            addCriterion("XMSX =", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotEqualTo(String value) {
            addCriterion("XMSX <>", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxGreaterThan(String value) {
            addCriterion("XMSX >", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxGreaterThanOrEqualTo(String value) {
            addCriterion("XMSX >=", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxLessThan(String value) {
            addCriterion("XMSX <", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxLessThanOrEqualTo(String value) {
            addCriterion("XMSX <=", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxLike(String value) {
            addCriterion("XMSX like", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotLike(String value) {
            addCriterion("XMSX not like", value, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxIn(List<String> values) {
            addCriterion("XMSX in", values, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotIn(List<String> values) {
            addCriterion("XMSX not in", values, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxBetween(String value1, String value2) {
            addCriterion("XMSX between", value1, value2, "xmsx");
            return (Criteria) this;
        }

        public Criteria andXmsxNotBetween(String value1, String value2) {
            addCriterion("XMSX not between", value1, value2, "xmsx");
            return (Criteria) this;
        }

        public Criteria andSrxmbmIsNull() {
            addCriterion("SRXMBM is null");
            return (Criteria) this;
        }

        public Criteria andSrxmbmIsNotNull() {
            addCriterion("SRXMBM is not null");
            return (Criteria) this;
        }

        public Criteria andSrxmbmEqualTo(String value) {
            addCriterion("SRXMBM =", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotEqualTo(String value) {
            addCriterion("SRXMBM <>", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmGreaterThan(String value) {
            addCriterion("SRXMBM >", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmGreaterThanOrEqualTo(String value) {
            addCriterion("SRXMBM >=", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmLessThan(String value) {
            addCriterion("SRXMBM <", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmLessThanOrEqualTo(String value) {
            addCriterion("SRXMBM <=", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmLike(String value) {
            addCriterion("SRXMBM like", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotLike(String value) {
            addCriterion("SRXMBM not like", value, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmIn(List<String> values) {
            addCriterion("SRXMBM in", values, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotIn(List<String> values) {
            addCriterion("SRXMBM not in", values, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmBetween(String value1, String value2) {
            addCriterion("SRXMBM between", value1, value2, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmbmNotBetween(String value1, String value2) {
            addCriterion("SRXMBM not between", value1, value2, "srxmbm");
            return (Criteria) this;
        }

        public Criteria andSrxmmcIsNull() {
            addCriterion("SRXMMC is null");
            return (Criteria) this;
        }

        public Criteria andSrxmmcIsNotNull() {
            addCriterion("SRXMMC is not null");
            return (Criteria) this;
        }

        public Criteria andSrxmmcEqualTo(String value) {
            addCriterion("SRXMMC =", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcNotEqualTo(String value) {
            addCriterion("SRXMMC <>", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcGreaterThan(String value) {
            addCriterion("SRXMMC >", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcGreaterThanOrEqualTo(String value) {
            addCriterion("SRXMMC >=", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcLessThan(String value) {
            addCriterion("SRXMMC <", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcLessThanOrEqualTo(String value) {
            addCriterion("SRXMMC <=", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcLike(String value) {
            addCriterion("SRXMMC like", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcNotLike(String value) {
            addCriterion("SRXMMC not like", value, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcIn(List<String> values) {
            addCriterion("SRXMMC in", values, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcNotIn(List<String> values) {
            addCriterion("SRXMMC not in", values, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcBetween(String value1, String value2) {
            addCriterion("SRXMMC between", value1, value2, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andSrxmmcNotBetween(String value1, String value2) {
            addCriterion("SRXMMC not between", value1, value2, "srxmmc");
            return (Criteria) this;
        }

        public Criteria andZjxzbmIsNull() {
            addCriterion("ZJXZBM is null");
            return (Criteria) this;
        }

        public Criteria andZjxzbmIsNotNull() {
            addCriterion("ZJXZBM is not null");
            return (Criteria) this;
        }

        public Criteria andZjxzbmEqualTo(String value) {
            addCriterion("ZJXZBM =", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmNotEqualTo(String value) {
            addCriterion("ZJXZBM <>", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmGreaterThan(String value) {
            addCriterion("ZJXZBM >", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmGreaterThanOrEqualTo(String value) {
            addCriterion("ZJXZBM >=", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmLessThan(String value) {
            addCriterion("ZJXZBM <", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmLessThanOrEqualTo(String value) {
            addCriterion("ZJXZBM <=", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmLike(String value) {
            addCriterion("ZJXZBM like", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmNotLike(String value) {
            addCriterion("ZJXZBM not like", value, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmIn(List<String> values) {
            addCriterion("ZJXZBM in", values, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmNotIn(List<String> values) {
            addCriterion("ZJXZBM not in", values, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmBetween(String value1, String value2) {
            addCriterion("ZJXZBM between", value1, value2, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzbmNotBetween(String value1, String value2) {
            addCriterion("ZJXZBM not between", value1, value2, "zjxzbm");
            return (Criteria) this;
        }

        public Criteria andZjxzmcIsNull() {
            addCriterion("ZJXZMC is null");
            return (Criteria) this;
        }

        public Criteria andZjxzmcIsNotNull() {
            addCriterion("ZJXZMC is not null");
            return (Criteria) this;
        }

        public Criteria andZjxzmcEqualTo(String value) {
            addCriterion("ZJXZMC =", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcNotEqualTo(String value) {
            addCriterion("ZJXZMC <>", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcGreaterThan(String value) {
            addCriterion("ZJXZMC >", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcGreaterThanOrEqualTo(String value) {
            addCriterion("ZJXZMC >=", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcLessThan(String value) {
            addCriterion("ZJXZMC <", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcLessThanOrEqualTo(String value) {
            addCriterion("ZJXZMC <=", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcLike(String value) {
            addCriterion("ZJXZMC like", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcNotLike(String value) {
            addCriterion("ZJXZMC not like", value, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcIn(List<String> values) {
            addCriterion("ZJXZMC in", values, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcNotIn(List<String> values) {
            addCriterion("ZJXZMC not in", values, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcBetween(String value1, String value2) {
            addCriterion("ZJXZMC between", value1, value2, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andZjxzmcNotBetween(String value1, String value2) {
            addCriterion("ZJXZMC not between", value1, value2, "zjxzmc");
            return (Criteria) this;
        }

        public Criteria andYskmbmIsNull() {
            addCriterion("YSKMBM is null");
            return (Criteria) this;
        }

        public Criteria andYskmbmIsNotNull() {
            addCriterion("YSKMBM is not null");
            return (Criteria) this;
        }

        public Criteria andYskmbmEqualTo(String value) {
            addCriterion("YSKMBM =", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmNotEqualTo(String value) {
            addCriterion("YSKMBM <>", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmGreaterThan(String value) {
            addCriterion("YSKMBM >", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmGreaterThanOrEqualTo(String value) {
            addCriterion("YSKMBM >=", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmLessThan(String value) {
            addCriterion("YSKMBM <", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmLessThanOrEqualTo(String value) {
            addCriterion("YSKMBM <=", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmLike(String value) {
            addCriterion("YSKMBM like", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmNotLike(String value) {
            addCriterion("YSKMBM not like", value, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmIn(List<String> values) {
            addCriterion("YSKMBM in", values, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmNotIn(List<String> values) {
            addCriterion("YSKMBM not in", values, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmBetween(String value1, String value2) {
            addCriterion("YSKMBM between", value1, value2, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmbmNotBetween(String value1, String value2) {
            addCriterion("YSKMBM not between", value1, value2, "yskmbm");
            return (Criteria) this;
        }

        public Criteria andYskmmcIsNull() {
            addCriterion("YSKMMC is null");
            return (Criteria) this;
        }

        public Criteria andYskmmcIsNotNull() {
            addCriterion("YSKMMC is not null");
            return (Criteria) this;
        }

        public Criteria andYskmmcEqualTo(String value) {
            addCriterion("YSKMMC =", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcNotEqualTo(String value) {
            addCriterion("YSKMMC <>", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcGreaterThan(String value) {
            addCriterion("YSKMMC >", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcGreaterThanOrEqualTo(String value) {
            addCriterion("YSKMMC >=", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcLessThan(String value) {
            addCriterion("YSKMMC <", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcLessThanOrEqualTo(String value) {
            addCriterion("YSKMMC <=", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcLike(String value) {
            addCriterion("YSKMMC like", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcNotLike(String value) {
            addCriterion("YSKMMC not like", value, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcIn(List<String> values) {
            addCriterion("YSKMMC in", values, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcNotIn(List<String> values) {
            addCriterion("YSKMMC not in", values, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcBetween(String value1, String value2) {
            addCriterion("YSKMMC between", value1, value2, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andYskmmcNotBetween(String value1, String value2) {
            addCriterion("YSKMMC not between", value1, value2, "yskmmc");
            return (Criteria) this;
        }

        public Criteria andSjbzIsNull() {
            addCriterion("SJBZ is null");
            return (Criteria) this;
        }

        public Criteria andSjbzIsNotNull() {
            addCriterion("SJBZ is not null");
            return (Criteria) this;
        }

        public Criteria andSjbzEqualTo(String value) {
            addCriterion("SJBZ =", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzNotEqualTo(String value) {
            addCriterion("SJBZ <>", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzGreaterThan(String value) {
            addCriterion("SJBZ >", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzGreaterThanOrEqualTo(String value) {
            addCriterion("SJBZ >=", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzLessThan(String value) {
            addCriterion("SJBZ <", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzLessThanOrEqualTo(String value) {
            addCriterion("SJBZ <=", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzLike(String value) {
            addCriterion("SJBZ like", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzNotLike(String value) {
            addCriterion("SJBZ not like", value, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzIn(List<String> values) {
            addCriterion("SJBZ in", values, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzNotIn(List<String> values) {
            addCriterion("SJBZ not in", values, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzBetween(String value1, String value2) {
            addCriterion("SJBZ between", value1, value2, "sjbz");
            return (Criteria) this;
        }

        public Criteria andSjbzNotBetween(String value1, String value2) {
            addCriterion("SJBZ not between", value1, value2, "sjbz");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhIsNull() {
            addCriterion("CFJDSBH is null");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhIsNotNull() {
            addCriterion("CFJDSBH is not null");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhEqualTo(String value) {
            addCriterion("CFJDSBH =", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhNotEqualTo(String value) {
            addCriterion("CFJDSBH <>", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhGreaterThan(String value) {
            addCriterion("CFJDSBH >", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhGreaterThanOrEqualTo(String value) {
            addCriterion("CFJDSBH >=", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhLessThan(String value) {
            addCriterion("CFJDSBH <", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhLessThanOrEqualTo(String value) {
            addCriterion("CFJDSBH <=", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhLike(String value) {
            addCriterion("CFJDSBH like", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhNotLike(String value) {
            addCriterion("CFJDSBH not like", value, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhIn(List<String> values) {
            addCriterion("CFJDSBH in", values, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhNotIn(List<String> values) {
            addCriterion("CFJDSBH not in", values, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhBetween(String value1, String value2) {
            addCriterion("CFJDSBH between", value1, value2, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andCfjdsbhNotBetween(String value1, String value2) {
            addCriterion("CFJDSBH not between", value1, value2, "cfjdsbh");
            return (Criteria) this;
        }

        public Criteria andFzxmmcIsNull() {
            addCriterion("FZXMMC is null");
            return (Criteria) this;
        }

        public Criteria andFzxmmcIsNotNull() {
            addCriterion("FZXMMC is not null");
            return (Criteria) this;
        }

        public Criteria andFzxmmcEqualTo(String value) {
            addCriterion("FZXMMC =", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcNotEqualTo(String value) {
            addCriterion("FZXMMC <>", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcGreaterThan(String value) {
            addCriterion("FZXMMC >", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcGreaterThanOrEqualTo(String value) {
            addCriterion("FZXMMC >=", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcLessThan(String value) {
            addCriterion("FZXMMC <", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcLessThanOrEqualTo(String value) {
            addCriterion("FZXMMC <=", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcLike(String value) {
            addCriterion("FZXMMC like", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcNotLike(String value) {
            addCriterion("FZXMMC not like", value, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcIn(List<String> values) {
            addCriterion("FZXMMC in", values, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcNotIn(List<String> values) {
            addCriterion("FZXMMC not in", values, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcBetween(String value1, String value2) {
            addCriterion("FZXMMC between", value1, value2, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andFzxmmcNotBetween(String value1, String value2) {
            addCriterion("FZXMMC not between", value1, value2, "fzxmmc");
            return (Criteria) this;
        }

        public Criteria andJnshenggkIsNull() {
            addCriterion("JNSHENGGK is null");
            return (Criteria) this;
        }

        public Criteria andJnshenggkIsNotNull() {
            addCriterion("JNSHENGGK is not null");
            return (Criteria) this;
        }

        public Criteria andJnshenggkEqualTo(BigDecimal value) {
            addCriterion("JNSHENGGK =", value, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkNotEqualTo(BigDecimal value) {
            addCriterion("JNSHENGGK <>", value, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkGreaterThan(BigDecimal value) {
            addCriterion("JNSHENGGK >", value, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JNSHENGGK >=", value, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkLessThan(BigDecimal value) {
            addCriterion("JNSHENGGK <", value, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JNSHENGGK <=", value, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkIn(List<BigDecimal> values) {
            addCriterion("JNSHENGGK in", values, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkNotIn(List<BigDecimal> values) {
            addCriterion("JNSHENGGK not in", values, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JNSHENGGK between", value1, value2, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshenggkNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JNSHENGGK not between", value1, value2, "jnshenggk");
            return (Criteria) this;
        }

        public Criteria andJnshigkIsNull() {
            addCriterion("JNSHIGK is null");
            return (Criteria) this;
        }

        public Criteria andJnshigkIsNotNull() {
            addCriterion("JNSHIGK is not null");
            return (Criteria) this;
        }

        public Criteria andJnshigkEqualTo(BigDecimal value) {
            addCriterion("JNSHIGK =", value, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkNotEqualTo(BigDecimal value) {
            addCriterion("JNSHIGK <>", value, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkGreaterThan(BigDecimal value) {
            addCriterion("JNSHIGK >", value, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JNSHIGK >=", value, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkLessThan(BigDecimal value) {
            addCriterion("JNSHIGK <", value, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JNSHIGK <=", value, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkIn(List<BigDecimal> values) {
            addCriterion("JNSHIGK in", values, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkNotIn(List<BigDecimal> values) {
            addCriterion("JNSHIGK not in", values, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JNSHIGK between", value1, value2, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJnshigkNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JNSHIGK not between", value1, value2, "jnshigk");
            return (Criteria) this;
        }

        public Criteria andJzmjIsNull() {
            addCriterion("JZMJ is null");
            return (Criteria) this;
        }

        public Criteria andJzmjIsNotNull() {
            addCriterion("JZMJ is not null");
            return (Criteria) this;
        }

        public Criteria andJzmjEqualTo(BigDecimal value) {
            addCriterion("JZMJ =", value, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjNotEqualTo(BigDecimal value) {
            addCriterion("JZMJ <>", value, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjGreaterThan(BigDecimal value) {
            addCriterion("JZMJ >", value, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JZMJ >=", value, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjLessThan(BigDecimal value) {
            addCriterion("JZMJ <", value, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JZMJ <=", value, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjIn(List<BigDecimal> values) {
            addCriterion("JZMJ in", values, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjNotIn(List<BigDecimal> values) {
            addCriterion("JZMJ not in", values, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JZMJ between", value1, value2, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJzmjNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JZMJ not between", value1, value2, "jzmj");
            return (Criteria) this;
        }

        public Criteria andJldwIsNull() {
            addCriterion("JLDW is null");
            return (Criteria) this;
        }

        public Criteria andJldwIsNotNull() {
            addCriterion("JLDW is not null");
            return (Criteria) this;
        }

        public Criteria andJldwEqualTo(String value) {
            addCriterion("JLDW =", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwNotEqualTo(String value) {
            addCriterion("JLDW <>", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwGreaterThan(String value) {
            addCriterion("JLDW >", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwGreaterThanOrEqualTo(String value) {
            addCriterion("JLDW >=", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwLessThan(String value) {
            addCriterion("JLDW <", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwLessThanOrEqualTo(String value) {
            addCriterion("JLDW <=", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwLike(String value) {
            addCriterion("JLDW like", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwNotLike(String value) {
            addCriterion("JLDW not like", value, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwIn(List<String> values) {
            addCriterion("JLDW in", values, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwNotIn(List<String> values) {
            addCriterion("JLDW not in", values, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwBetween(String value1, String value2) {
            addCriterion("JLDW between", value1, value2, "jldw");
            return (Criteria) this;
        }

        public Criteria andJldwNotBetween(String value1, String value2) {
            addCriterion("JLDW not between", value1, value2, "jldw");
            return (Criteria) this;
        }

        public Criteria andSlIsNull() {
            addCriterion("SL is null");
            return (Criteria) this;
        }

        public Criteria andSlIsNotNull() {
            addCriterion("SL is not null");
            return (Criteria) this;
        }

        public Criteria andSlEqualTo(BigDecimal value) {
            addCriterion("SL =", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotEqualTo(BigDecimal value) {
            addCriterion("SL <>", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThan(BigDecimal value) {
            addCriterion("SL >", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SL >=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThan(BigDecimal value) {
            addCriterion("SL <", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SL <=", value, "sl");
            return (Criteria) this;
        }

        public Criteria andSlIn(List<BigDecimal> values) {
            addCriterion("SL in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotIn(List<BigDecimal> values) {
            addCriterion("SL not in", values, "sl");
            return (Criteria) this;
        }

        public Criteria andSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SL between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SL not between", value1, value2, "sl");
            return (Criteria) this;
        }

        public Criteria andJeIsNull() {
            addCriterion("JE is null");
            return (Criteria) this;
        }

        public Criteria andJeIsNotNull() {
            addCriterion("JE is not null");
            return (Criteria) this;
        }

        public Criteria andJeEqualTo(BigDecimal value) {
            addCriterion("JE =", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotEqualTo(BigDecimal value) {
            addCriterion("JE <>", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThan(BigDecimal value) {
            addCriterion("JE >", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JE >=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThan(BigDecimal value) {
            addCriterion("JE <", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JE <=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeIn(List<BigDecimal> values) {
            addCriterion("JE in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotIn(List<BigDecimal> values) {
            addCriterion("JE not in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE not between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNull() {
            addCriterion("BYZD1 is null");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNotNull() {
            addCriterion("BYZD1 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd1EqualTo(String value) {
            addCriterion("BYZD1 =", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotEqualTo(String value) {
            addCriterion("BYZD1 <>", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThan(String value) {
            addCriterion("BYZD1 >", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD1 >=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThan(String value) {
            addCriterion("BYZD1 <", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThanOrEqualTo(String value) {
            addCriterion("BYZD1 <=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Like(String value) {
            addCriterion("BYZD1 like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotLike(String value) {
            addCriterion("BYZD1 not like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1In(List<String> values) {
            addCriterion("BYZD1 in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotIn(List<String> values) {
            addCriterion("BYZD1 not in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Between(String value1, String value2) {
            addCriterion("BYZD1 between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotBetween(String value1, String value2) {
            addCriterion("BYZD1 not between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNull() {
            addCriterion("BYZD2 is null");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNotNull() {
            addCriterion("BYZD2 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd2EqualTo(String value) {
            addCriterion("BYZD2 =", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotEqualTo(String value) {
            addCriterion("BYZD2 <>", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThan(String value) {
            addCriterion("BYZD2 >", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD2 >=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThan(String value) {
            addCriterion("BYZD2 <", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThanOrEqualTo(String value) {
            addCriterion("BYZD2 <=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Like(String value) {
            addCriterion("BYZD2 like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotLike(String value) {
            addCriterion("BYZD2 not like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2In(List<String> values) {
            addCriterion("BYZD2 in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotIn(List<String> values) {
            addCriterion("BYZD2 not in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Between(String value1, String value2) {
            addCriterion("BYZD2 between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotBetween(String value1, String value2) {
            addCriterion("BYZD2 not between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNull() {
            addCriterion("BYZD3 is null");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNotNull() {
            addCriterion("BYZD3 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd3EqualTo(String value) {
            addCriterion("BYZD3 =", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotEqualTo(String value) {
            addCriterion("BYZD3 <>", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThan(String value) {
            addCriterion("BYZD3 >", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD3 >=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThan(String value) {
            addCriterion("BYZD3 <", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThanOrEqualTo(String value) {
            addCriterion("BYZD3 <=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Like(String value) {
            addCriterion("BYZD3 like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotLike(String value) {
            addCriterion("BYZD3 not like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3In(List<String> values) {
            addCriterion("BYZD3 in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotIn(List<String> values) {
            addCriterion("BYZD3 not in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Between(String value1, String value2) {
            addCriterion("BYZD3 between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotBetween(String value1, String value2) {
            addCriterion("BYZD3 not between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(String value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(String value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(String value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(String value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(String value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLike(String value) {
            addCriterion("OPER_DATE like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotLike(String value) {
            addCriterion("OPER_DATE not like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<String> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<String> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(String value1, String value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(String value1, String value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(String value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(String value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(String value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(String value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLike(String value) {
            addCriterion("OPER_TIME like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotLike(String value) {
            addCriterion("OPER_TIME not like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<String> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<String> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(String value1, String value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(String value1, String value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andPjzlIsNull() {
            addCriterion("PJZL is null");
            return (Criteria) this;
        }

        public Criteria andPjzlIsNotNull() {
            addCriterion("PJZL is not null");
            return (Criteria) this;
        }

        public Criteria andPjzlEqualTo(String value) {
            addCriterion("PJZL =", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotEqualTo(String value) {
            addCriterion("PJZL <>", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlGreaterThan(String value) {
            addCriterion("PJZL >", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlGreaterThanOrEqualTo(String value) {
            addCriterion("PJZL >=", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlLessThan(String value) {
            addCriterion("PJZL <", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlLessThanOrEqualTo(String value) {
            addCriterion("PJZL <=", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlLike(String value) {
            addCriterion("PJZL like", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotLike(String value) {
            addCriterion("PJZL not like", value, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlIn(List<String> values) {
            addCriterion("PJZL in", values, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotIn(List<String> values) {
            addCriterion("PJZL not in", values, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlBetween(String value1, String value2) {
            addCriterion("PJZL between", value1, value2, "pjzl");
            return (Criteria) this;
        }

        public Criteria andPjzlNotBetween(String value1, String value2) {
            addCriterion("PJZL not between", value1, value2, "pjzl");
            return (Criteria) this;
        }

        public Criteria andJksbhIsNull() {
            addCriterion("JKSBH is null");
            return (Criteria) this;
        }

        public Criteria andJksbhIsNotNull() {
            addCriterion("JKSBH is not null");
            return (Criteria) this;
        }

        public Criteria andJksbhEqualTo(String value) {
            addCriterion("JKSBH =", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotEqualTo(String value) {
            addCriterion("JKSBH <>", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhGreaterThan(String value) {
            addCriterion("JKSBH >", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhGreaterThanOrEqualTo(String value) {
            addCriterion("JKSBH >=", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhLessThan(String value) {
            addCriterion("JKSBH <", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhLessThanOrEqualTo(String value) {
            addCriterion("JKSBH <=", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhLike(String value) {
            addCriterion("JKSBH like", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotLike(String value) {
            addCriterion("JKSBH not like", value, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhIn(List<String> values) {
            addCriterion("JKSBH in", values, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotIn(List<String> values) {
            addCriterion("JKSBH not in", values, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhBetween(String value1, String value2) {
            addCriterion("JKSBH between", value1, value2, "jksbh");
            return (Criteria) this;
        }

        public Criteria andJksbhNotBetween(String value1, String value2) {
            addCriterion("JKSBH not between", value1, value2, "jksbh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 24 11:41:37 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}