package fnt.repository.model;

import java.math.BigDecimal;

public class FsQdfPaymentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.PKID
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.PJZL
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String pjzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.JKSBH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String jksbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.XZQH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String xzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.ZSFS
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String zsfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.JKFS
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String jkfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.TZRQ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String tzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.WTZSDWBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String wtzsdwbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.WTZSDWMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String wtzsdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String wtdwzgbmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String wtdwzgbmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.WTZSBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String wtzsbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.STZSDWBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String stzsdwbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.STZSDWMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String stzsdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.STDWZGBMBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String stdwzgbmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.STDWZGBMMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String stdwzgbmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.ZSDWZZJG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String zsdwzzjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.FKRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String fkrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.FKRKHH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String fkrkhh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.FKRZH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String fkrzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.SKRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String skrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.SKRKHH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String skrkhh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.SKRZH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String skrzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.ZJE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private BigDecimal zje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.SGPBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String sgpbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.FMYY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String fmyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.FMLY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String fmly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.DSFY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String dsfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BGRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String bgrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.AY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String ay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.AH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String ah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.ZDJH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String zdjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BDE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String bde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.XZSPDTWYM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String xzspdtwym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BYZD1
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String byzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BYZD2
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String byzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BYZD3
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String byzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String hostBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String hostChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.QDF_BOOK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String qdfBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.QDF_CHK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String qdfChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.YHWDBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String yhwdbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.JYM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String jym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.LXSKBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String lxskbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.YHSKRQ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String yhskrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.DBPYWXH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String dbpywxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.OPERID
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.CBS_ACT_SERIAL
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String cbsActSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.PENDING_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String pendingFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.PENDING_DATE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String pendingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.CHK_ACT_DT
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String chkActDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_INFO.BMKYWXH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    private String bmkywxh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.PKID
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.PKID
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.PKID
     *
     * @param pkid the value for FIS.FS_QDF_PAYMENT_INFO.PKID
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.PJZL
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.PJZL
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getPjzl() {
        return pjzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.PJZL
     *
     * @param pjzl the value for FIS.FS_QDF_PAYMENT_INFO.PJZL
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setPjzl(String pjzl) {
        this.pjzl = pjzl == null ? null : pjzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.JKSBH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.JKSBH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getJksbh() {
        return jksbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.JKSBH
     *
     * @param jksbh the value for FIS.FS_QDF_PAYMENT_INFO.JKSBH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setJksbh(String jksbh) {
        this.jksbh = jksbh == null ? null : jksbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.XZQH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.XZQH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.XZQH
     *
     * @param xzqh the value for FIS.FS_QDF_PAYMENT_INFO.XZQH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZSFS
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.ZSFS
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getZsfs() {
        return zsfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZSFS
     *
     * @param zsfs the value for FIS.FS_QDF_PAYMENT_INFO.ZSFS
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setZsfs(String zsfs) {
        this.zsfs = zsfs == null ? null : zsfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.JKFS
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.JKFS
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getJkfs() {
        return jkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.JKFS
     *
     * @param jkfs the value for FIS.FS_QDF_PAYMENT_INFO.JKFS
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setJkfs(String jkfs) {
        this.jkfs = jkfs == null ? null : jkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.TZRQ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.TZRQ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getTzrq() {
        return tzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.TZRQ
     *
     * @param tzrq the value for FIS.FS_QDF_PAYMENT_INFO.TZRQ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setTzrq(String tzrq) {
        this.tzrq = tzrq == null ? null : tzrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTZSDWBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.WTZSDWBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getWtzsdwbm() {
        return wtzsdwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTZSDWBM
     *
     * @param wtzsdwbm the value for FIS.FS_QDF_PAYMENT_INFO.WTZSDWBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setWtzsdwbm(String wtzsdwbm) {
        this.wtzsdwbm = wtzsdwbm == null ? null : wtzsdwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTZSDWMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.WTZSDWMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getWtzsdwmc() {
        return wtzsdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTZSDWMC
     *
     * @param wtzsdwmc the value for FIS.FS_QDF_PAYMENT_INFO.WTZSDWMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setWtzsdwmc(String wtzsdwmc) {
        this.wtzsdwmc = wtzsdwmc == null ? null : wtzsdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getWtdwzgbmbm() {
        return wtdwzgbmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMBM
     *
     * @param wtdwzgbmbm the value for FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setWtdwzgbmbm(String wtdwzgbmbm) {
        this.wtdwzgbmbm = wtdwzgbmbm == null ? null : wtdwzgbmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getWtdwzgbmmc() {
        return wtdwzgbmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMMC
     *
     * @param wtdwzgbmmc the value for FIS.FS_QDF_PAYMENT_INFO.WTDWZGBMMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setWtdwzgbmmc(String wtdwzgbmmc) {
        this.wtdwzgbmmc = wtdwzgbmmc == null ? null : wtdwzgbmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTZSBZ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.WTZSBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getWtzsbz() {
        return wtzsbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.WTZSBZ
     *
     * @param wtzsbz the value for FIS.FS_QDF_PAYMENT_INFO.WTZSBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setWtzsbz(String wtzsbz) {
        this.wtzsbz = wtzsbz == null ? null : wtzsbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.STZSDWBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.STZSDWBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getStzsdwbm() {
        return stzsdwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.STZSDWBM
     *
     * @param stzsdwbm the value for FIS.FS_QDF_PAYMENT_INFO.STZSDWBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setStzsdwbm(String stzsdwbm) {
        this.stzsdwbm = stzsdwbm == null ? null : stzsdwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.STZSDWMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.STZSDWMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getStzsdwmc() {
        return stzsdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.STZSDWMC
     *
     * @param stzsdwmc the value for FIS.FS_QDF_PAYMENT_INFO.STZSDWMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setStzsdwmc(String stzsdwmc) {
        this.stzsdwmc = stzsdwmc == null ? null : stzsdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.STDWZGBMBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.STDWZGBMBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getStdwzgbmbm() {
        return stdwzgbmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.STDWZGBMBM
     *
     * @param stdwzgbmbm the value for FIS.FS_QDF_PAYMENT_INFO.STDWZGBMBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setStdwzgbmbm(String stdwzgbmbm) {
        this.stdwzgbmbm = stdwzgbmbm == null ? null : stdwzgbmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.STDWZGBMMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.STDWZGBMMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getStdwzgbmmc() {
        return stdwzgbmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.STDWZGBMMC
     *
     * @param stdwzgbmmc the value for FIS.FS_QDF_PAYMENT_INFO.STDWZGBMMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setStdwzgbmmc(String stdwzgbmmc) {
        this.stdwzgbmmc = stdwzgbmmc == null ? null : stdwzgbmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZSDWZZJG
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.ZSDWZZJG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getZsdwzzjg() {
        return zsdwzzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZSDWZZJG
     *
     * @param zsdwzzjg the value for FIS.FS_QDF_PAYMENT_INFO.ZSDWZZJG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setZsdwzzjg(String zsdwzzjg) {
        this.zsdwzzjg = zsdwzzjg == null ? null : zsdwzzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.FKRMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.FKRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getFkrmc() {
        return fkrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.FKRMC
     *
     * @param fkrmc the value for FIS.FS_QDF_PAYMENT_INFO.FKRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setFkrmc(String fkrmc) {
        this.fkrmc = fkrmc == null ? null : fkrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.FKRKHH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.FKRKHH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getFkrkhh() {
        return fkrkhh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.FKRKHH
     *
     * @param fkrkhh the value for FIS.FS_QDF_PAYMENT_INFO.FKRKHH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setFkrkhh(String fkrkhh) {
        this.fkrkhh = fkrkhh == null ? null : fkrkhh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.FKRZH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.FKRZH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getFkrzh() {
        return fkrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.FKRZH
     *
     * @param fkrzh the value for FIS.FS_QDF_PAYMENT_INFO.FKRZH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setFkrzh(String fkrzh) {
        this.fkrzh = fkrzh == null ? null : fkrzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.SKRMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.SKRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getSkrmc() {
        return skrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.SKRMC
     *
     * @param skrmc the value for FIS.FS_QDF_PAYMENT_INFO.SKRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setSkrmc(String skrmc) {
        this.skrmc = skrmc == null ? null : skrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.SKRKHH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.SKRKHH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getSkrkhh() {
        return skrkhh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.SKRKHH
     *
     * @param skrkhh the value for FIS.FS_QDF_PAYMENT_INFO.SKRKHH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setSkrkhh(String skrkhh) {
        this.skrkhh = skrkhh == null ? null : skrkhh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.SKRZH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.SKRZH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getSkrzh() {
        return skrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.SKRZH
     *
     * @param skrzh the value for FIS.FS_QDF_PAYMENT_INFO.SKRZH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setSkrzh(String skrzh) {
        this.skrzh = skrzh == null ? null : skrzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZJE
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.ZJE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public BigDecimal getZje() {
        return zje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZJE
     *
     * @param zje the value for FIS.FS_QDF_PAYMENT_INFO.ZJE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setZje(BigDecimal zje) {
        this.zje = zje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BZ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BZ
     *
     * @param bz the value for FIS.FS_QDF_PAYMENT_INFO.BZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.SGPBZ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.SGPBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getSgpbz() {
        return sgpbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.SGPBZ
     *
     * @param sgpbz the value for FIS.FS_QDF_PAYMENT_INFO.SGPBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setSgpbz(String sgpbz) {
        this.sgpbz = sgpbz == null ? null : sgpbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.FMYY
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.FMYY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getFmyy() {
        return fmyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.FMYY
     *
     * @param fmyy the value for FIS.FS_QDF_PAYMENT_INFO.FMYY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setFmyy(String fmyy) {
        this.fmyy = fmyy == null ? null : fmyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.FMLY
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.FMLY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getFmly() {
        return fmly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.FMLY
     *
     * @param fmly the value for FIS.FS_QDF_PAYMENT_INFO.FMLY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setFmly(String fmly) {
        this.fmly = fmly == null ? null : fmly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.DSFY
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.DSFY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getDsfy() {
        return dsfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.DSFY
     *
     * @param dsfy the value for FIS.FS_QDF_PAYMENT_INFO.DSFY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setDsfy(String dsfy) {
        this.dsfy = dsfy == null ? null : dsfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BGRMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BGRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getBgrmc() {
        return bgrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BGRMC
     *
     * @param bgrmc the value for FIS.FS_QDF_PAYMENT_INFO.BGRMC
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setBgrmc(String bgrmc) {
        this.bgrmc = bgrmc == null ? null : bgrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.AY
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.AY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getAy() {
        return ay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.AY
     *
     * @param ay the value for FIS.FS_QDF_PAYMENT_INFO.AY
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setAy(String ay) {
        this.ay = ay == null ? null : ay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.AH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.AH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getAh() {
        return ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.AH
     *
     * @param ah the value for FIS.FS_QDF_PAYMENT_INFO.AH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setAh(String ah) {
        this.ah = ah == null ? null : ah.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZDJH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.ZDJH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getZdjh() {
        return zdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.ZDJH
     *
     * @param zdjh the value for FIS.FS_QDF_PAYMENT_INFO.ZDJH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setZdjh(String zdjh) {
        this.zdjh = zdjh == null ? null : zdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BDE
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BDE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getBde() {
        return bde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BDE
     *
     * @param bde the value for FIS.FS_QDF_PAYMENT_INFO.BDE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setBde(String bde) {
        this.bde = bde == null ? null : bde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.XZSPDTWYM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.XZSPDTWYM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getXzspdtwym() {
        return xzspdtwym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.XZSPDTWYM
     *
     * @param xzspdtwym the value for FIS.FS_QDF_PAYMENT_INFO.XZSPDTWYM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setXzspdtwym(String xzspdtwym) {
        this.xzspdtwym = xzspdtwym == null ? null : xzspdtwym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BYZD1
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BYZD1
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getByzd1() {
        return byzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BYZD1
     *
     * @param byzd1 the value for FIS.FS_QDF_PAYMENT_INFO.BYZD1
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setByzd1(String byzd1) {
        this.byzd1 = byzd1 == null ? null : byzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BYZD2
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BYZD2
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getByzd2() {
        return byzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BYZD2
     *
     * @param byzd2 the value for FIS.FS_QDF_PAYMENT_INFO.BYZD2
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setByzd2(String byzd2) {
        this.byzd2 = byzd2 == null ? null : byzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BYZD3
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BYZD3
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getByzd3() {
        return byzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BYZD3
     *
     * @param byzd3 the value for FIS.FS_QDF_PAYMENT_INFO.BYZD3
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setByzd3(String byzd3) {
        this.byzd3 = byzd3 == null ? null : byzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getHostBookFlag() {
        return hostBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @param hostBookFlag the value for FIS.FS_QDF_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setHostBookFlag(String hostBookFlag) {
        this.hostBookFlag = hostBookFlag == null ? null : hostBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getHostChkFlag() {
        return hostChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @param hostChkFlag the value for FIS.FS_QDF_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setHostChkFlag(String hostChkFlag) {
        this.hostChkFlag = hostChkFlag == null ? null : hostChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.QDF_BOOK_FLAG
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.QDF_BOOK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getQdfBookFlag() {
        return qdfBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.QDF_BOOK_FLAG
     *
     * @param qdfBookFlag the value for FIS.FS_QDF_PAYMENT_INFO.QDF_BOOK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setQdfBookFlag(String qdfBookFlag) {
        this.qdfBookFlag = qdfBookFlag == null ? null : qdfBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.QDF_CHK_FLAG
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.QDF_CHK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getQdfChkFlag() {
        return qdfChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.QDF_CHK_FLAG
     *
     * @param qdfChkFlag the value for FIS.FS_QDF_PAYMENT_INFO.QDF_CHK_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setQdfChkFlag(String qdfChkFlag) {
        this.qdfChkFlag = qdfChkFlag == null ? null : qdfChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.OPER_DATE
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.OPER_DATE
     *
     * @param operDate the value for FIS.FS_QDF_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.OPER_TIME
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.OPER_TIME
     *
     * @param operTime the value for FIS.FS_QDF_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.YHWDBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.YHWDBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getYhwdbm() {
        return yhwdbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.YHWDBM
     *
     * @param yhwdbm the value for FIS.FS_QDF_PAYMENT_INFO.YHWDBM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setYhwdbm(String yhwdbm) {
        this.yhwdbm = yhwdbm == null ? null : yhwdbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.JYM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.JYM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getJym() {
        return jym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.JYM
     *
     * @param jym the value for FIS.FS_QDF_PAYMENT_INFO.JYM
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setJym(String jym) {
        this.jym = jym == null ? null : jym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.LXSKBZ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.LXSKBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getLxskbz() {
        return lxskbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.LXSKBZ
     *
     * @param lxskbz the value for FIS.FS_QDF_PAYMENT_INFO.LXSKBZ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setLxskbz(String lxskbz) {
        this.lxskbz = lxskbz == null ? null : lxskbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.YHSKRQ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.YHSKRQ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getYhskrq() {
        return yhskrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.YHSKRQ
     *
     * @param yhskrq the value for FIS.FS_QDF_PAYMENT_INFO.YHSKRQ
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setYhskrq(String yhskrq) {
        this.yhskrq = yhskrq == null ? null : yhskrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.DBPYWXH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.DBPYWXH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getDbpywxh() {
        return dbpywxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.DBPYWXH
     *
     * @param dbpywxh the value for FIS.FS_QDF_PAYMENT_INFO.DBPYWXH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setDbpywxh(String dbpywxh) {
        this.dbpywxh = dbpywxh == null ? null : dbpywxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.OPERID
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.OPERID
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.OPERID
     *
     * @param operid the value for FIS.FS_QDF_PAYMENT_INFO.OPERID
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.CBS_ACT_SERIAL
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.CBS_ACT_SERIAL
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getCbsActSerial() {
        return cbsActSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.CBS_ACT_SERIAL
     *
     * @param cbsActSerial the value for FIS.FS_QDF_PAYMENT_INFO.CBS_ACT_SERIAL
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setCbsActSerial(String cbsActSerial) {
        this.cbsActSerial = cbsActSerial == null ? null : cbsActSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.PENDING_FLAG
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.PENDING_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getPendingFlag() {
        return pendingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.PENDING_FLAG
     *
     * @param pendingFlag the value for FIS.FS_QDF_PAYMENT_INFO.PENDING_FLAG
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setPendingFlag(String pendingFlag) {
        this.pendingFlag = pendingFlag == null ? null : pendingFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.PENDING_DATE
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.PENDING_DATE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getPendingDate() {
        return pendingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.PENDING_DATE
     *
     * @param pendingDate the value for FIS.FS_QDF_PAYMENT_INFO.PENDING_DATE
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setPendingDate(String pendingDate) {
        this.pendingDate = pendingDate == null ? null : pendingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.CHK_ACT_DT
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.CHK_ACT_DT
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getChkActDt() {
        return chkActDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.CHK_ACT_DT
     *
     * @param chkActDt the value for FIS.FS_QDF_PAYMENT_INFO.CHK_ACT_DT
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setChkActDt(String chkActDt) {
        this.chkActDt = chkActDt == null ? null : chkActDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_INFO.BMKYWXH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_INFO.BMKYWXH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public String getBmkywxh() {
        return bmkywxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_INFO.BMKYWXH
     *
     * @param bmkywxh the value for FIS.FS_QDF_PAYMENT_INFO.BMKYWXH
     *
     * @mbggenerated Sat Jul 06 02:14:25 CST 2013
     */
    public void setBmkywxh(String bmkywxh) {
        this.bmkywxh = bmkywxh == null ? null : bmkywxh.trim();
    }
}