package fnt.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FsQdfPendingTxnExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:25 CST 2013
     */
    public FsQdfPendingTxnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andXzqhIsNull() {
            addCriterion("XZQH is null");
            return (Criteria) this;
        }

        public Criteria andXzqhIsNotNull() {
            addCriterion("XZQH is not null");
            return (Criteria) this;
        }

        public Criteria andXzqhEqualTo(String value) {
            addCriterion("XZQH =", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotEqualTo(String value) {
            addCriterion("XZQH <>", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhGreaterThan(String value) {
            addCriterion("XZQH >", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhGreaterThanOrEqualTo(String value) {
            addCriterion("XZQH >=", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLessThan(String value) {
            addCriterion("XZQH <", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLessThanOrEqualTo(String value) {
            addCriterion("XZQH <=", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhLike(String value) {
            addCriterion("XZQH like", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotLike(String value) {
            addCriterion("XZQH not like", value, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhIn(List<String> values) {
            addCriterion("XZQH in", values, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotIn(List<String> values) {
            addCriterion("XZQH not in", values, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhBetween(String value1, String value2) {
            addCriterion("XZQH between", value1, value2, "xzqh");
            return (Criteria) this;
        }

        public Criteria andXzqhNotBetween(String value1, String value2) {
            addCriterion("XZQH not between", value1, value2, "xzqh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhIsNull() {
            addCriterion("BMKYWXH is null");
            return (Criteria) this;
        }

        public Criteria andBmkywxhIsNotNull() {
            addCriterion("BMKYWXH is not null");
            return (Criteria) this;
        }

        public Criteria andBmkywxhEqualTo(String value) {
            addCriterion("BMKYWXH =", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotEqualTo(String value) {
            addCriterion("BMKYWXH <>", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhGreaterThan(String value) {
            addCriterion("BMKYWXH >", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhGreaterThanOrEqualTo(String value) {
            addCriterion("BMKYWXH >=", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhLessThan(String value) {
            addCriterion("BMKYWXH <", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhLessThanOrEqualTo(String value) {
            addCriterion("BMKYWXH <=", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhLike(String value) {
            addCriterion("BMKYWXH like", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotLike(String value) {
            addCriterion("BMKYWXH not like", value, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhIn(List<String> values) {
            addCriterion("BMKYWXH in", values, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotIn(List<String> values) {
            addCriterion("BMKYWXH not in", values, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhBetween(String value1, String value2) {
            addCriterion("BMKYWXH between", value1, value2, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andBmkywxhNotBetween(String value1, String value2) {
            addCriterion("BMKYWXH not between", value1, value2, "bmkywxh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhIsNull() {
            addCriterion("CZZHZH is null");
            return (Criteria) this;
        }

        public Criteria andCzzhzhIsNotNull() {
            addCriterion("CZZHZH is not null");
            return (Criteria) this;
        }

        public Criteria andCzzhzhEqualTo(String value) {
            addCriterion("CZZHZH =", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotEqualTo(String value) {
            addCriterion("CZZHZH <>", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhGreaterThan(String value) {
            addCriterion("CZZHZH >", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhGreaterThanOrEqualTo(String value) {
            addCriterion("CZZHZH >=", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhLessThan(String value) {
            addCriterion("CZZHZH <", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhLessThanOrEqualTo(String value) {
            addCriterion("CZZHZH <=", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhLike(String value) {
            addCriterion("CZZHZH like", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotLike(String value) {
            addCriterion("CZZHZH not like", value, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhIn(List<String> values) {
            addCriterion("CZZHZH in", values, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotIn(List<String> values) {
            addCriterion("CZZHZH not in", values, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhBetween(String value1, String value2) {
            addCriterion("CZZHZH between", value1, value2, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andCzzhzhNotBetween(String value1, String value2) {
            addCriterion("CZZHZH not between", value1, value2, "czzhzh");
            return (Criteria) this;
        }

        public Criteria andJkfsIsNull() {
            addCriterion("JKFS is null");
            return (Criteria) this;
        }

        public Criteria andJkfsIsNotNull() {
            addCriterion("JKFS is not null");
            return (Criteria) this;
        }

        public Criteria andJkfsEqualTo(String value) {
            addCriterion("JKFS =", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotEqualTo(String value) {
            addCriterion("JKFS <>", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsGreaterThan(String value) {
            addCriterion("JKFS >", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsGreaterThanOrEqualTo(String value) {
            addCriterion("JKFS >=", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLessThan(String value) {
            addCriterion("JKFS <", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLessThanOrEqualTo(String value) {
            addCriterion("JKFS <=", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsLike(String value) {
            addCriterion("JKFS like", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotLike(String value) {
            addCriterion("JKFS not like", value, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsIn(List<String> values) {
            addCriterion("JKFS in", values, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotIn(List<String> values) {
            addCriterion("JKFS not in", values, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsBetween(String value1, String value2) {
            addCriterion("JKFS between", value1, value2, "jkfs");
            return (Criteria) this;
        }

        public Criteria andJkfsNotBetween(String value1, String value2) {
            addCriterion("JKFS not between", value1, value2, "jkfs");
            return (Criteria) this;
        }

        public Criteria andYtIsNull() {
            addCriterion("YT is null");
            return (Criteria) this;
        }

        public Criteria andYtIsNotNull() {
            addCriterion("YT is not null");
            return (Criteria) this;
        }

        public Criteria andYtEqualTo(String value) {
            addCriterion("YT =", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotEqualTo(String value) {
            addCriterion("YT <>", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtGreaterThan(String value) {
            addCriterion("YT >", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtGreaterThanOrEqualTo(String value) {
            addCriterion("YT >=", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLessThan(String value) {
            addCriterion("YT <", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLessThanOrEqualTo(String value) {
            addCriterion("YT <=", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLike(String value) {
            addCriterion("YT like", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotLike(String value) {
            addCriterion("YT not like", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtIn(List<String> values) {
            addCriterion("YT in", values, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotIn(List<String> values) {
            addCriterion("YT not in", values, "yt");
            return (Criteria) this;
        }

        public Criteria andYtBetween(String value1, String value2) {
            addCriterion("YT between", value1, value2, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotBetween(String value1, String value2) {
            addCriterion("YT not between", value1, value2, "yt");
            return (Criteria) this;
        }

        public Criteria andJeIsNull() {
            addCriterion("JE is null");
            return (Criteria) this;
        }

        public Criteria andJeIsNotNull() {
            addCriterion("JE is not null");
            return (Criteria) this;
        }

        public Criteria andJeEqualTo(BigDecimal value) {
            addCriterion("JE =", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotEqualTo(BigDecimal value) {
            addCriterion("JE <>", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThan(BigDecimal value) {
            addCriterion("JE >", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JE >=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThan(BigDecimal value) {
            addCriterion("JE <", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JE <=", value, "je");
            return (Criteria) this;
        }

        public Criteria andJeIn(List<BigDecimal> values) {
            addCriterion("JE in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotIn(List<BigDecimal> values) {
            addCriterion("JE not in", values, "je");
            return (Criteria) this;
        }

        public Criteria andJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JE not between", value1, value2, "je");
            return (Criteria) this;
        }

        public Criteria andJyrqIsNull() {
            addCriterion("JYRQ is null");
            return (Criteria) this;
        }

        public Criteria andJyrqIsNotNull() {
            addCriterion("JYRQ is not null");
            return (Criteria) this;
        }

        public Criteria andJyrqEqualTo(String value) {
            addCriterion("JYRQ =", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotEqualTo(String value) {
            addCriterion("JYRQ <>", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqGreaterThan(String value) {
            addCriterion("JYRQ >", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqGreaterThanOrEqualTo(String value) {
            addCriterion("JYRQ >=", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqLessThan(String value) {
            addCriterion("JYRQ <", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqLessThanOrEqualTo(String value) {
            addCriterion("JYRQ <=", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqLike(String value) {
            addCriterion("JYRQ like", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotLike(String value) {
            addCriterion("JYRQ not like", value, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqIn(List<String> values) {
            addCriterion("JYRQ in", values, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotIn(List<String> values) {
            addCriterion("JYRQ not in", values, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqBetween(String value1, String value2) {
            addCriterion("JYRQ between", value1, value2, "jyrq");
            return (Criteria) this;
        }

        public Criteria andJyrqNotBetween(String value1, String value2) {
            addCriterion("JYRQ not between", value1, value2, "jyrq");
            return (Criteria) this;
        }

        public Criteria andTxacBridIsNull() {
            addCriterion("TXAC_BRID is null");
            return (Criteria) this;
        }

        public Criteria andTxacBridIsNotNull() {
            addCriterion("TXAC_BRID is not null");
            return (Criteria) this;
        }

        public Criteria andTxacBridEqualTo(String value) {
            addCriterion("TXAC_BRID =", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotEqualTo(String value) {
            addCriterion("TXAC_BRID <>", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridGreaterThan(String value) {
            addCriterion("TXAC_BRID >", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridGreaterThanOrEqualTo(String value) {
            addCriterion("TXAC_BRID >=", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLessThan(String value) {
            addCriterion("TXAC_BRID <", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLessThanOrEqualTo(String value) {
            addCriterion("TXAC_BRID <=", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLike(String value) {
            addCriterion("TXAC_BRID like", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotLike(String value) {
            addCriterion("TXAC_BRID not like", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridIn(List<String> values) {
            addCriterion("TXAC_BRID in", values, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotIn(List<String> values) {
            addCriterion("TXAC_BRID not in", values, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridBetween(String value1, String value2) {
            addCriterion("TXAC_BRID between", value1, value2, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotBetween(String value1, String value2) {
            addCriterion("TXAC_BRID not between", value1, value2, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andBookOperidIsNull() {
            addCriterion("BOOK_OPERID is null");
            return (Criteria) this;
        }

        public Criteria andBookOperidIsNotNull() {
            addCriterion("BOOK_OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andBookOperidEqualTo(String value) {
            addCriterion("BOOK_OPERID =", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidNotEqualTo(String value) {
            addCriterion("BOOK_OPERID <>", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidGreaterThan(String value) {
            addCriterion("BOOK_OPERID >", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidGreaterThanOrEqualTo(String value) {
            addCriterion("BOOK_OPERID >=", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidLessThan(String value) {
            addCriterion("BOOK_OPERID <", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidLessThanOrEqualTo(String value) {
            addCriterion("BOOK_OPERID <=", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidLike(String value) {
            addCriterion("BOOK_OPERID like", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidNotLike(String value) {
            addCriterion("BOOK_OPERID not like", value, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidIn(List<String> values) {
            addCriterion("BOOK_OPERID in", values, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidNotIn(List<String> values) {
            addCriterion("BOOK_OPERID not in", values, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidBetween(String value1, String value2) {
            addCriterion("BOOK_OPERID between", value1, value2, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andBookOperidNotBetween(String value1, String value2) {
            addCriterion("BOOK_OPERID not between", value1, value2, "bookOperid");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(String value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(String value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(String value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(String value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLike(String value) {
            addCriterion("OPER_TIME like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotLike(String value) {
            addCriterion("OPER_TIME not like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<String> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<String> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(String value1, String value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(String value1, String value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNull() {
            addCriterion("BYZD1 is null");
            return (Criteria) this;
        }

        public Criteria andByzd1IsNotNull() {
            addCriterion("BYZD1 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd1EqualTo(String value) {
            addCriterion("BYZD1 =", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotEqualTo(String value) {
            addCriterion("BYZD1 <>", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThan(String value) {
            addCriterion("BYZD1 >", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD1 >=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThan(String value) {
            addCriterion("BYZD1 <", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1LessThanOrEqualTo(String value) {
            addCriterion("BYZD1 <=", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Like(String value) {
            addCriterion("BYZD1 like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotLike(String value) {
            addCriterion("BYZD1 not like", value, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1In(List<String> values) {
            addCriterion("BYZD1 in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotIn(List<String> values) {
            addCriterion("BYZD1 not in", values, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1Between(String value1, String value2) {
            addCriterion("BYZD1 between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd1NotBetween(String value1, String value2) {
            addCriterion("BYZD1 not between", value1, value2, "byzd1");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNull() {
            addCriterion("BYZD2 is null");
            return (Criteria) this;
        }

        public Criteria andByzd2IsNotNull() {
            addCriterion("BYZD2 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd2EqualTo(String value) {
            addCriterion("BYZD2 =", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotEqualTo(String value) {
            addCriterion("BYZD2 <>", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThan(String value) {
            addCriterion("BYZD2 >", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD2 >=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThan(String value) {
            addCriterion("BYZD2 <", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2LessThanOrEqualTo(String value) {
            addCriterion("BYZD2 <=", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Like(String value) {
            addCriterion("BYZD2 like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotLike(String value) {
            addCriterion("BYZD2 not like", value, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2In(List<String> values) {
            addCriterion("BYZD2 in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotIn(List<String> values) {
            addCriterion("BYZD2 not in", values, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2Between(String value1, String value2) {
            addCriterion("BYZD2 between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd2NotBetween(String value1, String value2) {
            addCriterion("BYZD2 not between", value1, value2, "byzd2");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNull() {
            addCriterion("BYZD3 is null");
            return (Criteria) this;
        }

        public Criteria andByzd3IsNotNull() {
            addCriterion("BYZD3 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd3EqualTo(String value) {
            addCriterion("BYZD3 =", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotEqualTo(String value) {
            addCriterion("BYZD3 <>", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThan(String value) {
            addCriterion("BYZD3 >", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD3 >=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThan(String value) {
            addCriterion("BYZD3 <", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3LessThanOrEqualTo(String value) {
            addCriterion("BYZD3 <=", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Like(String value) {
            addCriterion("BYZD3 like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotLike(String value) {
            addCriterion("BYZD3 not like", value, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3In(List<String> values) {
            addCriterion("BYZD3 in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotIn(List<String> values) {
            addCriterion("BYZD3 not in", values, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3Between(String value1, String value2) {
            addCriterion("BYZD3 between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd3NotBetween(String value1, String value2) {
            addCriterion("BYZD3 not between", value1, value2, "byzd3");
            return (Criteria) this;
        }

        public Criteria andByzd4IsNull() {
            addCriterion("BYZD4 is null");
            return (Criteria) this;
        }

        public Criteria andByzd4IsNotNull() {
            addCriterion("BYZD4 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd4EqualTo(String value) {
            addCriterion("BYZD4 =", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotEqualTo(String value) {
            addCriterion("BYZD4 <>", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4GreaterThan(String value) {
            addCriterion("BYZD4 >", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD4 >=", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4LessThan(String value) {
            addCriterion("BYZD4 <", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4LessThanOrEqualTo(String value) {
            addCriterion("BYZD4 <=", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4Like(String value) {
            addCriterion("BYZD4 like", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotLike(String value) {
            addCriterion("BYZD4 not like", value, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4In(List<String> values) {
            addCriterion("BYZD4 in", values, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotIn(List<String> values) {
            addCriterion("BYZD4 not in", values, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4Between(String value1, String value2) {
            addCriterion("BYZD4 between", value1, value2, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd4NotBetween(String value1, String value2) {
            addCriterion("BYZD4 not between", value1, value2, "byzd4");
            return (Criteria) this;
        }

        public Criteria andByzd5IsNull() {
            addCriterion("BYZD5 is null");
            return (Criteria) this;
        }

        public Criteria andByzd5IsNotNull() {
            addCriterion("BYZD5 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd5EqualTo(String value) {
            addCriterion("BYZD5 =", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotEqualTo(String value) {
            addCriterion("BYZD5 <>", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5GreaterThan(String value) {
            addCriterion("BYZD5 >", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD5 >=", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5LessThan(String value) {
            addCriterion("BYZD5 <", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5LessThanOrEqualTo(String value) {
            addCriterion("BYZD5 <=", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5Like(String value) {
            addCriterion("BYZD5 like", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotLike(String value) {
            addCriterion("BYZD5 not like", value, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5In(List<String> values) {
            addCriterion("BYZD5 in", values, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotIn(List<String> values) {
            addCriterion("BYZD5 not in", values, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5Between(String value1, String value2) {
            addCriterion("BYZD5 between", value1, value2, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd5NotBetween(String value1, String value2) {
            addCriterion("BYZD5 not between", value1, value2, "byzd5");
            return (Criteria) this;
        }

        public Criteria andByzd6IsNull() {
            addCriterion("BYZD6 is null");
            return (Criteria) this;
        }

        public Criteria andByzd6IsNotNull() {
            addCriterion("BYZD6 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd6EqualTo(String value) {
            addCriterion("BYZD6 =", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotEqualTo(String value) {
            addCriterion("BYZD6 <>", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6GreaterThan(String value) {
            addCriterion("BYZD6 >", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD6 >=", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6LessThan(String value) {
            addCriterion("BYZD6 <", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6LessThanOrEqualTo(String value) {
            addCriterion("BYZD6 <=", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6Like(String value) {
            addCriterion("BYZD6 like", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotLike(String value) {
            addCriterion("BYZD6 not like", value, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6In(List<String> values) {
            addCriterion("BYZD6 in", values, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotIn(List<String> values) {
            addCriterion("BYZD6 not in", values, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6Between(String value1, String value2) {
            addCriterion("BYZD6 between", value1, value2, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd6NotBetween(String value1, String value2) {
            addCriterion("BYZD6 not between", value1, value2, "byzd6");
            return (Criteria) this;
        }

        public Criteria andByzd7IsNull() {
            addCriterion("BYZD7 is null");
            return (Criteria) this;
        }

        public Criteria andByzd7IsNotNull() {
            addCriterion("BYZD7 is not null");
            return (Criteria) this;
        }

        public Criteria andByzd7EqualTo(String value) {
            addCriterion("BYZD7 =", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotEqualTo(String value) {
            addCriterion("BYZD7 <>", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7GreaterThan(String value) {
            addCriterion("BYZD7 >", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7GreaterThanOrEqualTo(String value) {
            addCriterion("BYZD7 >=", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7LessThan(String value) {
            addCriterion("BYZD7 <", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7LessThanOrEqualTo(String value) {
            addCriterion("BYZD7 <=", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7Like(String value) {
            addCriterion("BYZD7 like", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotLike(String value) {
            addCriterion("BYZD7 not like", value, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7In(List<String> values) {
            addCriterion("BYZD7 in", values, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotIn(List<String> values) {
            addCriterion("BYZD7 not in", values, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7Between(String value1, String value2) {
            addCriterion("BYZD7 between", value1, value2, "byzd7");
            return (Criteria) this;
        }

        public Criteria andByzd7NotBetween(String value1, String value2) {
            addCriterion("BYZD7 not between", value1, value2, "byzd7");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 08 20:57:26 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_QDF_PENDING_TXN
     *
     * @mbggenerated Mon Jul 08 20:57:26 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}