package fnt.repository.model;

import java.math.BigDecimal;

public class FsQdfShareInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.PKID
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.PJZL
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String pjzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.JKSBH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String jksbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCXZQH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hcxzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCZGBMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hczgbmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCZGBMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hczgbmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCDWBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hcdwbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCDWMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hcdwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCXMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hcxmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCXMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hcxmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCZJXZBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hczjxzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCZJXZMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hczjxzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.YSKMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String yskmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.YSKMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String yskmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCZHMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hczhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCZH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hczh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCKHHMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hckhhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HCYHLB
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hcyhlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.HRXZQH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String hrxzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.FCJE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private BigDecimal fcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.OPER_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.OPER_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.APPLY_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.APPLY_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.SHARE_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String shareDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.SHARE_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String shareTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_SHARE_INFO.SHARE_STATUS
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    private String shareStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.PKID
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.PKID
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.PKID
     *
     * @param pkid the value for FIS.FS_QDF_SHARE_INFO.PKID
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.PJZL
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.PJZL
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getPjzl() {
        return pjzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.PJZL
     *
     * @param pjzl the value for FIS.FS_QDF_SHARE_INFO.PJZL
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setPjzl(String pjzl) {
        this.pjzl = pjzl == null ? null : pjzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.JKSBH
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.JKSBH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getJksbh() {
        return jksbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.JKSBH
     *
     * @param jksbh the value for FIS.FS_QDF_SHARE_INFO.JKSBH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setJksbh(String jksbh) {
        this.jksbh = jksbh == null ? null : jksbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCXZQH
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCXZQH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHcxzqh() {
        return hcxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCXZQH
     *
     * @param hcxzqh the value for FIS.FS_QDF_SHARE_INFO.HCXZQH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHcxzqh(String hcxzqh) {
        this.hcxzqh = hcxzqh == null ? null : hcxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCZGBMBM
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCZGBMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHczgbmbm() {
        return hczgbmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCZGBMBM
     *
     * @param hczgbmbm the value for FIS.FS_QDF_SHARE_INFO.HCZGBMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHczgbmbm(String hczgbmbm) {
        this.hczgbmbm = hczgbmbm == null ? null : hczgbmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCZGBMMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCZGBMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHczgbmmc() {
        return hczgbmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCZGBMMC
     *
     * @param hczgbmmc the value for FIS.FS_QDF_SHARE_INFO.HCZGBMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHczgbmmc(String hczgbmmc) {
        this.hczgbmmc = hczgbmmc == null ? null : hczgbmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCDWBM
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCDWBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHcdwbm() {
        return hcdwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCDWBM
     *
     * @param hcdwbm the value for FIS.FS_QDF_SHARE_INFO.HCDWBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHcdwbm(String hcdwbm) {
        this.hcdwbm = hcdwbm == null ? null : hcdwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCDWMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCDWMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHcdwmc() {
        return hcdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCDWMC
     *
     * @param hcdwmc the value for FIS.FS_QDF_SHARE_INFO.HCDWMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHcdwmc(String hcdwmc) {
        this.hcdwmc = hcdwmc == null ? null : hcdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCXMBM
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCXMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHcxmbm() {
        return hcxmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCXMBM
     *
     * @param hcxmbm the value for FIS.FS_QDF_SHARE_INFO.HCXMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHcxmbm(String hcxmbm) {
        this.hcxmbm = hcxmbm == null ? null : hcxmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCXMMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCXMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHcxmmc() {
        return hcxmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCXMMC
     *
     * @param hcxmmc the value for FIS.FS_QDF_SHARE_INFO.HCXMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHcxmmc(String hcxmmc) {
        this.hcxmmc = hcxmmc == null ? null : hcxmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCZJXZBM
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCZJXZBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHczjxzbm() {
        return hczjxzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCZJXZBM
     *
     * @param hczjxzbm the value for FIS.FS_QDF_SHARE_INFO.HCZJXZBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHczjxzbm(String hczjxzbm) {
        this.hczjxzbm = hczjxzbm == null ? null : hczjxzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCZJXZMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCZJXZMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHczjxzmc() {
        return hczjxzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCZJXZMC
     *
     * @param hczjxzmc the value for FIS.FS_QDF_SHARE_INFO.HCZJXZMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHczjxzmc(String hczjxzmc) {
        this.hczjxzmc = hczjxzmc == null ? null : hczjxzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.YSKMBM
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.YSKMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getYskmbm() {
        return yskmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.YSKMBM
     *
     * @param yskmbm the value for FIS.FS_QDF_SHARE_INFO.YSKMBM
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setYskmbm(String yskmbm) {
        this.yskmbm = yskmbm == null ? null : yskmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.YSKMMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.YSKMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getYskmmc() {
        return yskmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.YSKMMC
     *
     * @param yskmmc the value for FIS.FS_QDF_SHARE_INFO.YSKMMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setYskmmc(String yskmmc) {
        this.yskmmc = yskmmc == null ? null : yskmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCZHMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCZHMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHczhmc() {
        return hczhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCZHMC
     *
     * @param hczhmc the value for FIS.FS_QDF_SHARE_INFO.HCZHMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHczhmc(String hczhmc) {
        this.hczhmc = hczhmc == null ? null : hczhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCZH
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCZH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHczh() {
        return hczh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCZH
     *
     * @param hczh the value for FIS.FS_QDF_SHARE_INFO.HCZH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHczh(String hczh) {
        this.hczh = hczh == null ? null : hczh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCKHHMC
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCKHHMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHckhhmc() {
        return hckhhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCKHHMC
     *
     * @param hckhhmc the value for FIS.FS_QDF_SHARE_INFO.HCKHHMC
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHckhhmc(String hckhhmc) {
        this.hckhhmc = hckhhmc == null ? null : hckhhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HCYHLB
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HCYHLB
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHcyhlb() {
        return hcyhlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HCYHLB
     *
     * @param hcyhlb the value for FIS.FS_QDF_SHARE_INFO.HCYHLB
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHcyhlb(String hcyhlb) {
        this.hcyhlb = hcyhlb == null ? null : hcyhlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.HRXZQH
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.HRXZQH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getHrxzqh() {
        return hrxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.HRXZQH
     *
     * @param hrxzqh the value for FIS.FS_QDF_SHARE_INFO.HRXZQH
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setHrxzqh(String hrxzqh) {
        this.hrxzqh = hrxzqh == null ? null : hrxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.FCJE
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.FCJE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public BigDecimal getFcje() {
        return fcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.FCJE
     *
     * @param fcje the value for FIS.FS_QDF_SHARE_INFO.FCJE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setFcje(BigDecimal fcje) {
        this.fcje = fcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.OPER_DATE
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.OPER_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.OPER_DATE
     *
     * @param operDate the value for FIS.FS_QDF_SHARE_INFO.OPER_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.OPER_TIME
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.OPER_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.OPER_TIME
     *
     * @param operTime the value for FIS.FS_QDF_SHARE_INFO.OPER_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.APPLY_DATE
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.APPLY_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.APPLY_DATE
     *
     * @param applyDate the value for FIS.FS_QDF_SHARE_INFO.APPLY_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate == null ? null : applyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.APPLY_TIME
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.APPLY_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.APPLY_TIME
     *
     * @param applyTime the value for FIS.FS_QDF_SHARE_INFO.APPLY_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setApplyTime(String applyTime) {
        this.applyTime = applyTime == null ? null : applyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.SHARE_DATE
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.SHARE_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getShareDate() {
        return shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.SHARE_DATE
     *
     * @param shareDate the value for FIS.FS_QDF_SHARE_INFO.SHARE_DATE
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setShareDate(String shareDate) {
        this.shareDate = shareDate == null ? null : shareDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.SHARE_TIME
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.SHARE_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getShareTime() {
        return shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.SHARE_TIME
     *
     * @param shareTime the value for FIS.FS_QDF_SHARE_INFO.SHARE_TIME
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setShareTime(String shareTime) {
        this.shareTime = shareTime == null ? null : shareTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_SHARE_INFO.SHARE_STATUS
     *
     * @return the value of FIS.FS_QDF_SHARE_INFO.SHARE_STATUS
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public String getShareStatus() {
        return shareStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_SHARE_INFO.SHARE_STATUS
     *
     * @param shareStatus the value for FIS.FS_QDF_SHARE_INFO.SHARE_STATUS
     *
     * @mbggenerated Sat Jul 06 00:33:30 CST 2013
     */
    public void setShareStatus(String shareStatus) {
        this.shareStatus = shareStatus == null ? null : shareStatus.trim();
    }
}