package fnt.repository.model;

import java.math.BigDecimal;

public class FsQdfPaymentItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.XMSX
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String xmsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.SRXMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String srxmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.SRXMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String srxmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.ZJXZBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String zjxzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.ZJXZMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String zjxzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.YSKMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String yskmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.YSKMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String yskmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.SJBZ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String sjbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.CFJDSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String cfjdsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.FZXMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String fzxmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.JNSHENGGK
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal jnshenggk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.JNSHIGK
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal jnshigk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.JZMJ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal jzmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.JLDW
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String jldw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.SL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.JE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private BigDecimal je;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD1
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD2
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD3
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String byzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.OPER_DATE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.OPER_TIME
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.PJZL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String pjzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_QDF_PAYMENT_ITEM.JKSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    private String jksbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.PKID
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.PKID
     *
     * @param pkid the value for FIS.FS_QDF_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.XMSX
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.XMSX
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getXmsx() {
        return xmsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.XMSX
     *
     * @param xmsx the value for FIS.FS_QDF_PAYMENT_ITEM.XMSX
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setXmsx(String xmsx) {
        this.xmsx = xmsx == null ? null : xmsx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SRXMBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.SRXMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getSrxmbm() {
        return srxmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SRXMBM
     *
     * @param srxmbm the value for FIS.FS_QDF_PAYMENT_ITEM.SRXMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setSrxmbm(String srxmbm) {
        this.srxmbm = srxmbm == null ? null : srxmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SRXMMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.SRXMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getSrxmmc() {
        return srxmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SRXMMC
     *
     * @param srxmmc the value for FIS.FS_QDF_PAYMENT_ITEM.SRXMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setSrxmmc(String srxmmc) {
        this.srxmmc = srxmmc == null ? null : srxmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.ZJXZBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.ZJXZBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getZjxzbm() {
        return zjxzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.ZJXZBM
     *
     * @param zjxzbm the value for FIS.FS_QDF_PAYMENT_ITEM.ZJXZBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setZjxzbm(String zjxzbm) {
        this.zjxzbm = zjxzbm == null ? null : zjxzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.ZJXZMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.ZJXZMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getZjxzmc() {
        return zjxzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.ZJXZMC
     *
     * @param zjxzmc the value for FIS.FS_QDF_PAYMENT_ITEM.ZJXZMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setZjxzmc(String zjxzmc) {
        this.zjxzmc = zjxzmc == null ? null : zjxzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.YSKMBM
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.YSKMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getYskmbm() {
        return yskmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.YSKMBM
     *
     * @param yskmbm the value for FIS.FS_QDF_PAYMENT_ITEM.YSKMBM
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setYskmbm(String yskmbm) {
        this.yskmbm = yskmbm == null ? null : yskmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.YSKMMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.YSKMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getYskmmc() {
        return yskmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.YSKMMC
     *
     * @param yskmmc the value for FIS.FS_QDF_PAYMENT_ITEM.YSKMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setYskmmc(String yskmmc) {
        this.yskmmc = yskmmc == null ? null : yskmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SJBZ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.SJBZ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getSjbz() {
        return sjbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SJBZ
     *
     * @param sjbz the value for FIS.FS_QDF_PAYMENT_ITEM.SJBZ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setSjbz(String sjbz) {
        this.sjbz = sjbz == null ? null : sjbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.CFJDSBH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.CFJDSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getCfjdsbh() {
        return cfjdsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.CFJDSBH
     *
     * @param cfjdsbh the value for FIS.FS_QDF_PAYMENT_ITEM.CFJDSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setCfjdsbh(String cfjdsbh) {
        this.cfjdsbh = cfjdsbh == null ? null : cfjdsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.FZXMMC
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.FZXMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getFzxmmc() {
        return fzxmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.FZXMMC
     *
     * @param fzxmmc the value for FIS.FS_QDF_PAYMENT_ITEM.FZXMMC
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setFzxmmc(String fzxmmc) {
        this.fzxmmc = fzxmmc == null ? null : fzxmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JNSHENGGK
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.JNSHENGGK
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getJnshenggk() {
        return jnshenggk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JNSHENGGK
     *
     * @param jnshenggk the value for FIS.FS_QDF_PAYMENT_ITEM.JNSHENGGK
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJnshenggk(BigDecimal jnshenggk) {
        this.jnshenggk = jnshenggk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JNSHIGK
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.JNSHIGK
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getJnshigk() {
        return jnshigk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JNSHIGK
     *
     * @param jnshigk the value for FIS.FS_QDF_PAYMENT_ITEM.JNSHIGK
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJnshigk(BigDecimal jnshigk) {
        this.jnshigk = jnshigk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JZMJ
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.JZMJ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getJzmj() {
        return jzmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JZMJ
     *
     * @param jzmj the value for FIS.FS_QDF_PAYMENT_ITEM.JZMJ
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJzmj(BigDecimal jzmj) {
        this.jzmj = jzmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JLDW
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.JLDW
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getJldw() {
        return jldw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JLDW
     *
     * @param jldw the value for FIS.FS_QDF_PAYMENT_ITEM.JLDW
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJldw(String jldw) {
        this.jldw = jldw == null ? null : jldw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SL
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.SL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.SL
     *
     * @param sl the value for FIS.FS_QDF_PAYMENT_ITEM.SL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JE
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.JE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public BigDecimal getJe() {
        return je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JE
     *
     * @param je the value for FIS.FS_QDF_PAYMENT_ITEM.JE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJe(BigDecimal je) {
        this.je = je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD1
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.BYZD1
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd1() {
        return byzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD1
     *
     * @param byzd1 the value for FIS.FS_QDF_PAYMENT_ITEM.BYZD1
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd1(String byzd1) {
        this.byzd1 = byzd1 == null ? null : byzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD2
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.BYZD2
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd2() {
        return byzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD2
     *
     * @param byzd2 the value for FIS.FS_QDF_PAYMENT_ITEM.BYZD2
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd2(String byzd2) {
        this.byzd2 = byzd2 == null ? null : byzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD3
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.BYZD3
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getByzd3() {
        return byzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.BYZD3
     *
     * @param byzd3 the value for FIS.FS_QDF_PAYMENT_ITEM.BYZD3
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setByzd3(String byzd3) {
        this.byzd3 = byzd3 == null ? null : byzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.OPER_DATE
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.OPER_DATE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.OPER_DATE
     *
     * @param operDate the value for FIS.FS_QDF_PAYMENT_ITEM.OPER_DATE
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.OPER_TIME
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.OPER_TIME
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.OPER_TIME
     *
     * @param operTime the value for FIS.FS_QDF_PAYMENT_ITEM.OPER_TIME
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.PJZL
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.PJZL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getPjzl() {
        return pjzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.PJZL
     *
     * @param pjzl the value for FIS.FS_QDF_PAYMENT_ITEM.PJZL
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setPjzl(String pjzl) {
        this.pjzl = pjzl == null ? null : pjzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JKSBH
     *
     * @return the value of FIS.FS_QDF_PAYMENT_ITEM.JKSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public String getJksbh() {
        return jksbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_QDF_PAYMENT_ITEM.JKSBH
     *
     * @param jksbh the value for FIS.FS_QDF_PAYMENT_ITEM.JKSBH
     *
     * @mbggenerated Mon Jun 24 11:41:37 CST 2013
     */
    public void setJksbh(String jksbh) {
        this.jksbh = jksbh == null ? null : jksbh.trim();
    }
}